#!/usr/bin/env bash
# Cases for check-quick-xml-entry-points.sh (issue #1718), in the pattern of
# check-workflow-permissions.test.sh: add a case here before changing a rule.
#
# Each case writes a throwaway Cargo.lock and deny.toml fixture under
# $TMPDIR and runs the real guard script against them, so nothing here reads
# or depends on the repo's own Cargo.lock/deny.toml except the
# real-repo-files case at the end.
#
# No GNU-only sed/grep flags: this suite (and the guard it drives) must run
# the same way on macOS.
#
# Run: bash scripts/guards/check-quick-xml-entry-points.test.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../.." && pwd)"
GUARD="${HERE}/check-quick-xml-entry-points.sh"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/check-quick-xml-entry-points-test.XXXXXX")"
trap 'rm -rf "${TMP}"' EXIT

fails=0
passes=0

# check <name> <want-exit> <want-substring-or-empty> -- <args...>
# Reads the fixture lock/deny paths from the two args after --.
check() {
  local name="$1" want_rc="$2" want_sub="$3"
  shift 3
  [[ "${1:-}" == "--" ]] && shift
  local out rc=0
  out="$(bash "${GUARD}" "$@" 2>&1)" || rc=$?
  if [[ "${rc}" != "${want_rc}" ]]; then
    printf 'FAIL  %s: exit %s, wanted %s\n' "${name}" "${rc}" "${want_rc}"
    printf '%s\n' "${out}" | sed 's/^/      /'
    fails=$((fails + 1))
    return
  fi
  if [[ -n "${want_sub}" && "${out}" != *"${want_sub}"* ]]; then
    printf 'FAIL  %s: output missing %s\n' "${name}" "${want_sub}"
    printf '%s\n' "${out}" | sed 's/^/      /'
    fails=$((fails + 1))
    return
  fi
  printf 'ok    %s\n' "${name}"
  passes=$((passes + 1))
}

lock_two_parents() {
  local dir="$1"
  cat >"${dir}/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "inferno"
version = "0.11.21"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "ahash",
 "quick-xml 0.26.0",
 "rgb",
]

[[package]]
name = "object_store"
version = "0.13.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "async-trait",
 "bytes",
 "quick-xml 0.39.4",
 "reqwest",
]

[[package]]
name = "object_store"
version = "0.14.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "async-trait",
 "bytes",
 "quick-xml 0.41.0",
 "reqwest",
]

[[package]]
name = "quick-xml"
version = "0.26.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
]

[[package]]
name = "quick-xml"
version = "0.39.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
 "serde",
]

[[package]]
name = "quick-xml"
version = "0.41.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
 "serde",
]
LOCK
}

# --- comment_must_name_every_parent_of_an_affected_quick_xml ---------------

d="${TMP}/only-inferno-named"
mkdir -p "${d}"
lock_two_parents "${d}"
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: quick-xml enters through
  # inferno's SVG rendering only.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "comment_must_name_every_parent_of_an_affected_quick_xml: fixture naming only inferno fails and prints object_store" \
  1 "object_store" -- "${d}/Cargo.lock" "${d}/deny.toml"

d="${TMP}/both-named"
mkdir -p "${d}"
lock_two_parents "${d}"
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: quick-xml enters through
  # inferno 0.11.21's SVG rendering and through object_store 0.13.2.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "comment_must_name_every_parent_of_an_affected_quick_xml: corrected fixture naming both is clean" \
  0 "clean" -- "${d}/Cargo.lock" "${d}/deny.toml"

# A parent named without its own version does not count as documented: the
# comment must pair each parent with the version it resolves at in the lock,
# not just its bare name, so a later version bump cannot silently outrun the
# comment. Re-uses the both-named lock fixture but drops inferno's version
# number from the prose.
d="${TMP}/named-without-version"
mkdir -p "${d}"
lock_two_parents "${d}"
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: quick-xml enters through
  # inferno's SVG rendering and through object_store 0.13.2.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "a parent named without its own version still fails" \
  1 "inferno 0.11.21" -- "${d}/Cargo.lock" "${d}/deny.toml"

# A parent whose name is a substring of a longer identifier the comment DOES
# mention (here a fixture crate literally named "store", which is a
# substring of the real "object_store" text) must not be considered
# documented by that longer word: the match is anchored on word boundaries,
# not a bare substring test.
d="${TMP}/substring-name-anchoring"
mkdir -p "${d}"
cat >"${d}/Cargo.lock" <<'LOCK'
version = 4

[[package]]
name = "store"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "quick-xml",
]

[[package]]
name = "quick-xml"
version = "0.39.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
]
LOCK
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: enters through object_store
  # 1.0.0, not through a crate literally named "store".
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "a parent name that is only a substring of a longer word in the comment still fails" \
  1 "store 1.0.0" -- "${d}/Cargo.lock" "${d}/deny.toml"

# A named parent whose version in the lock has moved past what the comment
# says (object_store bumping from 0.13.2 to 0.14.1 while STILL resolving an
# affected quick-xml) must fail: the version pairing is what catches this,
# a bare name match would not.
d="${TMP}/version-drifted"
mkdir -p "${d}"
cat >"${d}/Cargo.lock" <<'LOCK'
version = 4

[[package]]
name = "object_store"
version = "0.14.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "quick-xml",
]

[[package]]
name = "quick-xml"
version = "0.39.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
]
LOCK
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: enters through object_store
  # 0.13.2 (stale: the lock fixture has since moved to 0.14.1).
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "a parent that bumped to a version the comment does not name still fails" \
  1 "object_store 0.14.1" -- "${d}/Cargo.lock" "${d}/deny.toml"

# A parent name that is only a substring away from what is written (e.g. the
# comment naming "object-store" with a hyphen, not the real crate name
# "object_store") must still fail: this is a literal-name check, not a fuzzy
# one.
d="${TMP}/wrong-spelling"
mkdir -p "${d}"
lock_two_parents "${d}"
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: enters through inferno and
  # object-store.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "a hyphenated misspelling of object_store still fails" \
  1 "object_store" -- "${d}/Cargo.lock" "${d}/deny.toml"

# --- zero_parents_found_is_a_failure ----------------------------------------

d="${TMP}/no-quick-xml-at-all"
mkdir -p "${d}"
cat >"${d}/Cargo.lock" <<'LOCK'
version = 4

[[package]]
name = "memchr"
version = "2.7.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
LOCK
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: not applicable, no quick-xml
  # in this fixture.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "zero_parents_found_is_a_failure: no quick-xml package in the lock exits 2" \
  2 "found zero direct parents" -- "${d}/Cargo.lock" "${d}/deny.toml"

d="${TMP}/only-unaffected-version"
mkdir -p "${d}"
cat >"${d}/Cargo.lock" <<'LOCK'
version = 4

[[package]]
name = "object_store"
version = "0.14.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "quick-xml",
]

[[package]]
name = "quick-xml"
version = "0.41.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
]
LOCK
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: not applicable, only the
  # fixed version is present.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "zero_parents_found_is_a_failure: only the fixed 0.41.0 version present exits 2" \
  2 "found zero direct parents" -- "${d}/Cargo.lock" "${d}/deny.toml"

# Single-version (bare "quick-xml", no version suffix) form of the
# dependency entry, which Cargo.lock uses when only one quick-xml version
# is in the graph. This must still be recognised as an affected version
# when that sole version is one of the affected ones.
d="${TMP}/bare-form-affected"
mkdir -p "${d}"
cat >"${d}/Cargo.lock" <<'LOCK'
version = 4

[[package]]
name = "inferno"
version = "0.11.21"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "quick-xml",
]

[[package]]
name = "quick-xml"
version = "0.26.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "memchr",
]
LOCK
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # RUSTSEC-2026-0194 and RUSTSEC-2026-0195: enters through inferno 0.11.21.
  "RUSTSEC-2026-0194",
  "RUSTSEC-2026-0195",
]
DENY
check "the bare single-version dependency form is recognised" \
  0 "clean" -- "${d}/Cargo.lock" "${d}/deny.toml"

# --- real repo files ---------------------------------------------------

check "the real repo Cargo.lock and deny.toml pass" 0 "clean" \
  -- "${REPO_ROOT}/Cargo.lock" "${REPO_ROOT}/deny.toml"

# --- usage -------------------------------------------------------------

out="$(bash "${GUARD}" /no/such/lock /no/such/deny 2>&1)"
rc=$?
if [[ "${rc}" == "64" && "${out}" == *"no such file"* ]]; then
  printf 'ok    a missing Cargo.lock path exits 64\n'
  passes=$((passes + 1))
else
  printf 'FAIL  a missing Cargo.lock path exits 64: got %s / %s\n' "${rc}" "${out}"
  fails=$((fails + 1))
fi

d="${TMP}/missing-deny"
mkdir -p "${d}"
lock_two_parents "${d}"
out="$(bash "${GUARD}" "${d}/Cargo.lock" "${d}/no-deny.toml" 2>&1)"
rc=$?
if [[ "${rc}" == "64" && "${out}" == *"no such file"* ]]; then
  printf 'ok    a missing deny.toml path exits 64\n'
  passes=$((passes + 1))
else
  printf 'FAIL  a missing deny.toml path exits 64: got %s / %s\n' "${rc}" "${out}"
  fails=$((fails + 1))
fi

out="$(bash "${GUARD}" a b c 2>&1)"
rc=$?
if [[ "${rc}" == "64" && "${out}" == *"unexpected extra argument"* ]]; then
  printf 'ok    a third positional argument exits 64\n'
  passes=$((passes + 1))
else
  printf 'FAIL  a third positional argument exits 64: got %s / %s\n' "${rc}" "${out}"
  fails=$((fails + 1))
fi

out="$(bash "${GUARD}" --help 2>&1)"
rc=$?
if [[ "${rc}" == "0" && "${out}" == *"RUSTSEC-2026-0194"* ]]; then
  printf 'ok    --help prints the header and exits 0\n'
  passes=$((passes + 1))
else
  printf 'FAIL  --help prints the header and exits 0: got %s / %s\n' "${rc}" "${out}"
  fails=$((fails + 1))
fi

# The anchor itself moved or was renamed in deny.toml: the guard must refuse
# rather than report a vacuous clean.
d="${TMP}/anchor-gone"
mkdir -p "${d}"
lock_two_parents "${d}"
cat >"${d}/deny.toml" <<'DENY'
[advisories]
ignore = [
  # No RUSTSEC line here at all.
]
DENY
check "a deny.toml missing the RUSTSEC-2026-0194 anchor refuses rather than passing" \
  2 "" -- "${d}/Cargo.lock" "${d}/deny.toml"

printf '\n%d passed, %d failed\n' "${passes}" "${fails}"
[[ "${fails}" -eq 0 ]]
