#!/usr/bin/env python3
"""gen_stats.py -- regenerate docs/explorer/stats.js from the cargo workspace.

Usage:
  python3 scripts/archmap/gen_stats.py [--repo <path>] [--out docs/explorer/stats.js]

Reads `cargo metadata --no-deps` and records, per workspace crate: the crate
directory relative to the repo, non-test Rust source files under src/ with
their line count, test files (tests/, benches/, and src files whose name ends
in _test.rs or lives under a tests/ dir), and the other workspace crates it
depends on (normal and dev dependencies kept separate), and every source file
with its line count so a curated module can own a single file of a large
crate. The explorer
page (docs/explorer/index.html) aggregates these per crate facts into the
modules declared in docs/explorer/map.js by directory prefix, so a curated
module can be renamed or regrouped without touching this script.

Also records the ADR count and the git commit the stats came from. The output
is deterministic for a given tree; commit it alongside map.js changes.
"""

import argparse
import json
import os
import subprocess
import sys


def run(cmd, cwd):
    return subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True).stdout


def count_lines(path):
    with open(path, "rb") as fh:
        return sum(1 for _ in fh)


def walk_rs(root):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in ("target", ".git"))
        for f in sorted(filenames):
            if f.endswith(".rs"):
                yield os.path.join(dirpath, f)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.path.join(os.path.dirname(__file__), "..", ".."))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    repo = os.path.abspath(args.repo)
    out_path = args.out or os.path.join(repo, "docs", "explorer", "stats.js")

    meta = json.loads(run(["cargo", "metadata", "--no-deps", "--format-version", "1"], repo))
    names = {p["name"] for p in meta["packages"]}
    packages = {}
    for p in meta["packages"]:
        crate_dir = os.path.dirname(p["manifest_path"])
        rel = os.path.relpath(crate_dir, repo)
        files = {}
        tests = 0
        loc = 0
        for path in walk_rs(crate_dir):
            r = os.path.relpath(path, crate_dir)
            n = count_lines(path)
            is_test = (
                r.startswith(("tests/", "benches/", "examples/"))
                or "/tests/" in r
                or r.endswith("_test.rs")
                or r.endswith("_tests.rs")
            )
            if is_test:
                tests += 1
            else:
                loc += n
                files[r] = n
        deps = sorted({d["name"] for d in p["dependencies"] if d["name"] in names and d["kind"] is None})
        dev_deps = sorted({d["name"] for d in p["dependencies"] if d["name"] in names and d["kind"] == "dev"})
        packages[rel] = {
            "name": p["name"],
            "files": len(files),
            "loc": loc,
            "tests": tests,
            "imports": deps,
            "devImports": dev_deps,
            "features": sorted(k for k in p.get("features", {}) if k != "default"),
            "sourceFiles": dict(sorted(files.items())),
        }

    adr_dir = os.path.join(repo, "docs", "adrs")
    adrs = len([f for f in os.listdir(adr_dir) if f.endswith(".md")]) if os.path.isdir(adr_dir) else 0
    commit = run(["git", "rev-parse", "--short", "HEAD"], repo).strip()
    date = run(["git", "log", "-1", "--format=%cs"], repo).strip()

    stats = {
        "commit": commit,
        "date": date,
        "adrs": adrs,
        "packages": dict(sorted(packages.items())),
    }
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("// Generated by scripts/archmap/gen_stats.py. Do not edit by hand.\n")
        fh.write("window.ARCHMAP_STATS = ")
        json.dump(stats, fh, indent=1, sort_keys=True)
        fh.write(";\n")
    print(f"wrote {os.path.relpath(out_path, repo)}: {len(packages)} crates @ {commit}", file=sys.stderr)


if __name__ == "__main__":
    main()
