//! Deterministic synthetic ClickBench fixture (ADR-2040, issue #2055 task
//! T5b). [`write_hits`] plants a 25-column, [`TOTAL_ROWS`]-row corpus across
//! four equal-sized parts (`hits_0.parquet`..`hits_3.parquet`) plus one
//! combined file (`hits.parquet`), so a later task's engines can mount
//! either shape under `suite.toml`'s table template. Every row is derived
//! only from a seed and its own index, so two runs with the same seed
//! produce byte-identical Parquet files.
//!
//! The column list is exactly the 25 distinct quoted identifiers referenced
//! across `benchmarks/clickbench/parquet/queries.sql` (verified by
//! `fn queries_sql_references_every_column` below): 4 as `Int64`, 3 as
//! `Int32`, 11 as `Int16`, `EventTime` as `Int64` (seconds, matching
//! upstream's `to_timestamp_seconds("EventTime")` queries), `EventDate` as
//! `UInt16` (days since the Unix epoch, matching `suite.toml`'s
//! `ravel.cast.EventDate = date-from-days` table option), and the 5
//! string-shaped columns as `Binary` with no UTF-8 annotation (matching
//! `suite.toml`'s `binary_as_string` table option).
//!
//! [`BASE_ROWS`] rows are generated by uniform-random draws (per-row, seeded
//! by index); four further blocks are planted on top for statements whose
//! `GROUP BY ... ORDER BY ... LIMIT 10 OFFSET <n>` shape the random base
//! alone cannot satisfy, because its OFFSET exceeds the number of distinct
//! groups the random rows happen to produce: Q39 (`Q39_BLOCK_ROWS` rows,
//! OFFSET 1000), Q41 (`Q41_BLOCK_ROWS` rows, OFFSET 100), Q42
//! (`Q42_BLOCK_ROWS` rows, OFFSET 10000), and Q43 (`Q43_BLOCK_ROWS` rows,
//! OFFSET 1000). Each block's rows satisfy that statement's `WHERE` by
//! construction and vary only the column(s) the statement groups by, so
//! every planted row is its own group and the group count equals the block
//! size. Q40 has the same OFFSET-1000 shape but is not planted: its `WHERE`
//! (`CounterID = 62 AND EventDate` in range `AND IsRefresh = 0`, with no
//! further restriction) already passes for roughly a quarter of
//! [`BASE_ROWS`]'s random rows (`CounterID = 62` at 30%, `IsRefresh = 0` at
//! 80%), and its `GROUP BY "TraficSourceID", "SearchEngineID", "AdvEngineID",
//! Src, Dst` key multiplies that row set out across 11 distinct
//! `TraficSourceID` values, 6 `SearchEngineID` values, and up to 500 distinct
//! `Dst` (`"URL"`) values, which is already far past 1,010 distinct groups
//! without any planting.
//!
//! Q28 and Q29 are not coverable by this fixture at all: both require a
//! `GROUP BY ... HAVING COUNT(*) > 100000` on a single `CounterID` value
//! (Q28) or a single `Referer` host (Q29), which demands one group holding
//! more rows than this fixture's entire row count. Both statements return
//! zero rows against every engine here; this fixture only exercises their
//! cardinality-zero agreement, never their `HAVING` clause.

use std::fs::File;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use datafusion::arrow::array::{
    ArrayRef, BinaryArray, Int16Array, Int32Array, Int64Array, UInt16Array,
};
use datafusion::arrow::datatypes::{DataType, Field, Schema, SchemaRef};
use datafusion::arrow::error::ArrowError;
use datafusion::arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;
use parquet::errors::ParquetError;
use rand::rngs::StdRng;
use rand::{RngExt, SeedableRng};

/// Row count generated by uniform-random, per-index draws, before any of
/// the targeted blocks below are appended.
pub const BASE_ROWS: usize = 10_000;
/// Rows planted for Q39 (`WHERE ... GROUP BY "URL" ... OFFSET 1000`): each
/// row carries a distinct `URL`, so the block contributes exactly this many
/// groups. Two more than the 1,010 OFFSET+LIMIT needs, as headroom.
const Q39_BLOCK_ROWS: usize = 1_012;
/// Rows planted for Q41 (`WHERE ... GROUP BY "URLHash", "EventDate" ...
/// OFFSET 100`): each row carries a distinct `URLHash` at a fixed
/// `EventDate`, so the block contributes exactly this many groups. Two
/// past the 110 OFFSET+LIMIT needs; the random base adds a few more by
/// chance, but the bound does not rely on them.
const Q41_BLOCK_ROWS: usize = 112;
/// Rows planted for Q42 (`WHERE ... GROUP BY "WindowClientWidth",
/// "WindowClientHeight" ... OFFSET 10000`): each row carries a distinct
/// `(WindowClientWidth, WindowClientHeight)` pair, so the block contributes
/// exactly this many groups: exactly the 10,010 OFFSET+LIMIT needs.
const Q42_BLOCK_ROWS: usize = 10_010;
/// Rows planted for Q43 (`WHERE ... GROUP BY DATE_TRUNC('minute',
/// "EventTime") ... OFFSET 1000`): each row carries a distinct
/// one-minute-truncated `EventTime` within a single day, so the block
/// contributes exactly this many groups: exactly the 1,010 OFFSET+LIMIT
/// needs.
const Q43_BLOCK_ROWS: usize = 1_010;
/// Total row count across the fixture's four parts: [`BASE_ROWS`] plus every
/// targeted block.
pub const TOTAL_ROWS: usize =
    BASE_ROWS + Q39_BLOCK_ROWS + Q41_BLOCK_ROWS + Q42_BLOCK_ROWS + Q43_BLOCK_ROWS;
/// Number of equal-sized parts `hits.parquet` is split across.
pub const PART_COUNT: usize = 4;
/// Row count of each `hits_<n>.parquet` part.
pub const ROWS_PER_PART: usize = TOTAL_ROWS / PART_COUNT;
const _: () = assert!(
    ROWS_PER_PART * PART_COUNT == TOTAL_ROWS,
    "TOTAL_ROWS must divide evenly across PART_COUNT parts"
);

/// `UserID` literal Q20 filters on (`"UserID" = 435090932899640449`),
/// planted on row 0.
const Q20_USER_ID: i64 = 435_090_932_899_640_449;
/// `URLHash` literal Q42 filters on, planted (with Q42's other conditions)
/// on row 1.
const Q42_URL_HASH: i64 = 2_868_770_270_353_813_622;
/// `RefererHash` literal Q41 filters on, planted (with Q41's other
/// conditions) on row 2.
const Q41_REFERER_HASH: i64 = 3_594_120_000_172_545_465;

/// `EventDate` span (days since the Unix epoch) covering upstream's
/// `"EventDate" >= '2013-07-01' AND "EventDate" <= '2013-07-31'` range
/// (Q37-42).
const EVENT_DATE_MIN: u16 = 15_887;
/// See [`EVENT_DATE_MIN`].
const EVENT_DATE_MAX: u16 = 15_917;
/// `EventDate` within Q43's narrower `'2013-07-14'..'2013-07-15'` range,
/// planted (with Q43's other conditions) on row 3.
const Q43_EVENT_DATE: u16 = 15_900;

/// 12 distinct, non-empty search phrases planted in as-equal-as-possible
/// counts among the rows with a non-empty `SearchPhrase`.
const SEARCH_PHRASES: [&str; 12] = [
    "rust programming",
    "object storage",
    "parquet format",
    "telemetry database",
    "query engine",
    "arrow columnar",
    "clickbench results",
    "multi tenant",
    "sql pushdown",
    "time series",
    "log segment",
    "flight protocol",
];

/// Distinct `MobilePhoneModel` values planted on the rows with a non-empty
/// model.
const MOBILE_MODELS: [&str; 6] = [
    "Model-0", "Model-1", "Model-2", "Model-3", "Model-4", "Model-5",
];

/// Everything [`write_hits`] can fail on.
#[derive(Debug, thiserror::Error)]
pub enum FixtureError {
    /// Creating or writing one of the output files failed.
    #[error("{path}: {source}")]
    Io {
        /// The file that failed.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: io::Error,
    },
    /// The Parquet writer itself refused a file.
    #[error("{path}: {source}")]
    Parquet {
        /// The file that failed.
        path: PathBuf,
        /// The underlying Parquet error.
        #[source]
        source: ParquetError,
    },
    /// Assembling a `RecordBatch` from the generated columns failed.
    #[error("building record batch: {0}")]
    Batch(#[from] ArrowError),
}

/// The fixture's Arrow schema, shared by every part and the combined file.
fn schema() -> SchemaRef {
    Arc::new(Schema::new(vec![
        Field::new("WatchID", DataType::Int64, false),
        Field::new("UserID", DataType::Int64, false),
        Field::new("URLHash", DataType::Int64, false),
        Field::new("RefererHash", DataType::Int64, false),
        Field::new("CounterID", DataType::Int32, false),
        Field::new("RegionID", DataType::Int32, false),
        Field::new("ClientIP", DataType::Int32, false),
        Field::new("AdvEngineID", DataType::Int16, false),
        Field::new("ResolutionWidth", DataType::Int16, false),
        Field::new("MobilePhone", DataType::Int16, false),
        Field::new("SearchEngineID", DataType::Int16, false),
        Field::new("TraficSourceID", DataType::Int16, false),
        Field::new("IsRefresh", DataType::Int16, false),
        Field::new("IsLink", DataType::Int16, false),
        Field::new("IsDownload", DataType::Int16, false),
        Field::new("DontCountHits", DataType::Int16, false),
        Field::new("WindowClientWidth", DataType::Int16, false),
        Field::new("WindowClientHeight", DataType::Int16, false),
        Field::new("EventTime", DataType::Int64, false),
        Field::new("EventDate", DataType::UInt16, false),
        Field::new("URL", DataType::Binary, false),
        Field::new("Title", DataType::Binary, false),
        Field::new("Referer", DataType::Binary, false),
        Field::new("SearchPhrase", DataType::Binary, false),
        Field::new("MobilePhoneModel", DataType::Binary, false),
    ]))
}

/// The 25 generated columns, each [`TOTAL_ROWS`] long, before being sliced
/// into parts.
struct Columns {
    watch_id: Vec<i64>,
    user_id: Vec<i64>,
    url_hash: Vec<i64>,
    referer_hash: Vec<i64>,
    counter_id: Vec<i32>,
    region_id: Vec<i32>,
    client_ip: Vec<i32>,
    adv_engine_id: Vec<i16>,
    resolution_width: Vec<i16>,
    mobile_phone: Vec<i16>,
    search_engine_id: Vec<i16>,
    trafic_source_id: Vec<i16>,
    is_refresh: Vec<i16>,
    is_link: Vec<i16>,
    is_download: Vec<i16>,
    dont_count_hits: Vec<i16>,
    window_client_width: Vec<i16>,
    window_client_height: Vec<i16>,
    event_time: Vec<i64>,
    event_date: Vec<u16>,
    url: Vec<Vec<u8>>,
    title: Vec<Vec<u8>>,
    referer: Vec<Vec<u8>>,
    search_phrase: Vec<Vec<u8>>,
    mobile_phone_model: Vec<Vec<u8>>,
}

impl Columns {
    fn with_capacity(n: usize) -> Self {
        Columns {
            watch_id: Vec::with_capacity(n),
            user_id: Vec::with_capacity(n),
            url_hash: Vec::with_capacity(n),
            referer_hash: Vec::with_capacity(n),
            counter_id: Vec::with_capacity(n),
            region_id: Vec::with_capacity(n),
            client_ip: Vec::with_capacity(n),
            adv_engine_id: Vec::with_capacity(n),
            resolution_width: Vec::with_capacity(n),
            mobile_phone: Vec::with_capacity(n),
            search_engine_id: Vec::with_capacity(n),
            trafic_source_id: Vec::with_capacity(n),
            is_refresh: Vec::with_capacity(n),
            is_link: Vec::with_capacity(n),
            is_download: Vec::with_capacity(n),
            dont_count_hits: Vec::with_capacity(n),
            window_client_width: Vec::with_capacity(n),
            window_client_height: Vec::with_capacity(n),
            event_time: Vec::with_capacity(n),
            event_date: Vec::with_capacity(n),
            url: Vec::with_capacity(n),
            title: Vec::with_capacity(n),
            referer: Vec::with_capacity(n),
            search_phrase: Vec::with_capacity(n),
            mobile_phone_model: Vec::with_capacity(n),
        }
    }

    /// Builds the `RecordBatch` for rows `start..end`.
    fn batch(
        &self,
        schema: &SchemaRef,
        start: usize,
        end: usize,
    ) -> Result<RecordBatch, FixtureError> {
        let arrays: Vec<ArrayRef> = vec![
            Arc::new(Int64Array::from(self.watch_id[start..end].to_vec())),
            Arc::new(Int64Array::from(self.user_id[start..end].to_vec())),
            Arc::new(Int64Array::from(self.url_hash[start..end].to_vec())),
            Arc::new(Int64Array::from(self.referer_hash[start..end].to_vec())),
            Arc::new(Int32Array::from(self.counter_id[start..end].to_vec())),
            Arc::new(Int32Array::from(self.region_id[start..end].to_vec())),
            Arc::new(Int32Array::from(self.client_ip[start..end].to_vec())),
            Arc::new(Int16Array::from(self.adv_engine_id[start..end].to_vec())),
            Arc::new(Int16Array::from(self.resolution_width[start..end].to_vec())),
            Arc::new(Int16Array::from(self.mobile_phone[start..end].to_vec())),
            Arc::new(Int16Array::from(self.search_engine_id[start..end].to_vec())),
            Arc::new(Int16Array::from(self.trafic_source_id[start..end].to_vec())),
            Arc::new(Int16Array::from(self.is_refresh[start..end].to_vec())),
            Arc::new(Int16Array::from(self.is_link[start..end].to_vec())),
            Arc::new(Int16Array::from(self.is_download[start..end].to_vec())),
            Arc::new(Int16Array::from(self.dont_count_hits[start..end].to_vec())),
            Arc::new(Int16Array::from(
                self.window_client_width[start..end].to_vec(),
            )),
            Arc::new(Int16Array::from(
                self.window_client_height[start..end].to_vec(),
            )),
            Arc::new(Int64Array::from(self.event_time[start..end].to_vec())),
            Arc::new(UInt16Array::from(self.event_date[start..end].to_vec())),
            Arc::new(BinaryArray::from_iter_values(self.url[start..end].iter())),
            Arc::new(BinaryArray::from_iter_values(self.title[start..end].iter())),
            Arc::new(BinaryArray::from_iter_values(
                self.referer[start..end].iter(),
            )),
            Arc::new(BinaryArray::from_iter_values(
                self.search_phrase[start..end].iter(),
            )),
            Arc::new(BinaryArray::from_iter_values(
                self.mobile_phone_model[start..end].iter(),
            )),
        ];
        Ok(RecordBatch::try_new(schema.clone(), arrays)?)
    }
}

/// A pool of `size` distinct `i64` values for a hash/id-shaped column, with
/// `literal` forced into slot 0 so a caller can plant it on a chosen row.
fn pool_with_literal(rng: &mut StdRng, size: usize, literal: i64) -> Vec<i64> {
    let mut pool = Vec::with_capacity(size);
    pool.push(literal);
    for _ in 1..size {
        pool.push(rng.random::<i64>());
    }
    pool
}

/// Generates all [`TOTAL_ROWS`] rows deterministically from `seed`.
fn generate(seed: u64) -> Columns {
    let mut rng = StdRng::seed_from_u64(seed);
    let mut cols = Columns::with_capacity(TOTAL_ROWS);

    let user_id_pool = pool_with_literal(&mut rng, 40, Q20_USER_ID);
    let url_hash_pool = pool_with_literal(&mut rng, 40, Q42_URL_HASH);
    let referer_hash_pool = pool_with_literal(&mut rng, 40, Q41_REFERER_HASH);

    let mut nonempty_phrase_count: usize = 0;

    for i in 0..BASE_ROWS {
        cols.watch_id
            .push((seed ^ 0x9E37_79B9_7F4A_7C15_u64).wrapping_add(i as u64) as i64);

        let mut user_id = user_id_pool[rng.random_range(0..user_id_pool.len())];
        let mut url_hash = url_hash_pool[rng.random_range(0..url_hash_pool.len())];
        let mut referer_hash = referer_hash_pool[rng.random_range(0..referer_hash_pool.len())];
        let mut counter_id: i32 = if rng.random_bool(0.30) {
            62
        } else {
            1 + rng.random_range(0..200)
        };
        let mut event_date: u16 =
            EVENT_DATE_MIN + rng.random_range(0..=(EVENT_DATE_MAX - EVENT_DATE_MIN));
        let mut is_refresh: i16 = i16::from(rng.random_bool(0.2));
        let mut dont_count_hits: i16 = i16::from(rng.random_bool(0.1));
        let mut trafic_source_id: i16 = rng.random_range(-1..=9);

        // Q20/Q41/Q42/Q43 each need a literal and a handful of co-occurring
        // filters; rows 0-3 plant them deterministically rather than relying
        // on chance over a 10,000-row, non-exhaustive sample.
        match i {
            0 => user_id = Q20_USER_ID,
            1 => {
                url_hash = Q42_URL_HASH;
                counter_id = 62;
                event_date = EVENT_DATE_MIN;
                is_refresh = 0;
                dont_count_hits = 0;
            }
            2 => {
                referer_hash = Q41_REFERER_HASH;
                counter_id = 62;
                event_date = Q43_EVENT_DATE;
                is_refresh = 0;
                trafic_source_id = -1;
            }
            3 => {
                counter_id = 62;
                event_date = Q43_EVENT_DATE;
                is_refresh = 0;
                dont_count_hits = 0;
            }
            _ => {}
        }

        cols.user_id.push(user_id);
        cols.url_hash.push(url_hash);
        cols.referer_hash.push(referer_hash);
        cols.counter_id.push(counter_id);
        cols.region_id.push(1 + rng.random_range(0..300));
        cols.client_ip.push(rng.random_range(0..(i32::MAX / 2)));
        cols.adv_engine_id.push(if rng.random_bool(0.1) {
            rng.random_range(1..20)
        } else {
            0
        });
        cols.resolution_width.push(rng.random_range(800..=2560));
        cols.mobile_phone.push(rng.random_range(0..=10));
        cols.search_engine_id.push(rng.random_range(0..=5));
        cols.trafic_source_id.push(trafic_source_id);
        cols.is_refresh.push(is_refresh);
        cols.is_link.push(i16::from(rng.random_bool(0.05)));
        cols.is_download.push(i16::from(rng.random_bool(0.05)));
        cols.dont_count_hits.push(dont_count_hits);
        cols.window_client_width.push(rng.random_range(0..=2000));
        cols.window_client_height.push(rng.random_range(0..=2000));

        let day_start = i64::from(event_date) * 86_400;
        cols.event_time
            .push(day_start + rng.random_range(0..86_400i64));
        cols.event_date.push(event_date);

        let url = if i % 20 == 0 {
            format!("http://www.google.com/search?q=rust&p={i}")
        } else {
            format!("http://example.com/page/{}", i % 500)
        };
        cols.url.push(url.into_bytes());

        let title = if i % 20 == 7 {
            format!("Google Result {i}")
        } else {
            format!("Example Page {}", i % 500)
        };
        cols.title.push(title.into_bytes());

        let referer = if i % 5 == 0 {
            Vec::new()
        } else {
            format!("https://host-{}.example/path/{i}", i % 8).into_bytes()
        };
        cols.referer.push(referer);

        let search_phrase = if i % 3 == 0 {
            Vec::new()
        } else {
            let phrase = SEARCH_PHRASES[nonempty_phrase_count % SEARCH_PHRASES.len()];
            nonempty_phrase_count += 1;
            phrase.as_bytes().to_vec()
        };
        cols.search_phrase.push(search_phrase);

        let mobile_phone_model = if i % 7 == 0 {
            MOBILE_MODELS[(i / 7) % MOBILE_MODELS.len()]
                .as_bytes()
                .to_vec()
        } else {
            Vec::new()
        };
        cols.mobile_phone_model.push(mobile_phone_model);
    }

    let mut next = BASE_ROWS;

    // Q39: CounterID=62, EventDate in range, IsRefresh=0, IsLink<>0,
    // IsDownload=0; a distinct URL per row makes every row its own
    // GROUP BY "URL" group.
    for local in 0..Q39_BLOCK_ROWS {
        let i = next;
        next += 1;
        cols.watch_id
            .push((seed ^ 0x9E37_79B9_7F4A_7C15_u64).wrapping_add(i as u64) as i64);
        cols.user_id.push(rng.random::<i64>());
        cols.url_hash.push(rng.random::<i64>());
        cols.referer_hash.push(rng.random::<i64>());
        cols.counter_id.push(62);
        cols.region_id.push(1 + rng.random_range(0..300));
        cols.client_ip.push(rng.random_range(0..(i32::MAX / 2)));
        cols.adv_engine_id.push(if rng.random_bool(0.1) {
            rng.random_range(1..20)
        } else {
            0
        });
        cols.resolution_width.push(rng.random_range(800..=2560));
        cols.mobile_phone.push(rng.random_range(0..=10));
        cols.search_engine_id.push(rng.random_range(0..=5));
        cols.trafic_source_id.push(rng.random_range(-1..=9));
        cols.is_refresh.push(0);
        cols.is_link.push(1);
        cols.is_download.push(0);
        cols.dont_count_hits.push(i16::from(rng.random_bool(0.1)));
        cols.window_client_width.push(rng.random_range(0..=2000));
        cols.window_client_height.push(rng.random_range(0..=2000));
        let day_start = i64::from(EVENT_DATE_MIN) * 86_400;
        cols.event_time
            .push(day_start + rng.random_range(0..86_400i64));
        cols.event_date.push(EVENT_DATE_MIN);
        cols.url
            .push(format!("http://example.com/q39/{local}").into_bytes());
        cols.title.push(Vec::new());
        cols.referer.push(Vec::new());
        cols.search_phrase.push(Vec::new());
        cols.mobile_phone_model.push(Vec::new());
    }

    // Q41: CounterID=62, EventDate in range, IsRefresh=0, TraficSourceID in
    // (-1, 6), RefererHash = Q41_REFERER_HASH; a distinct URLHash per row at
    // a fixed EventDate makes every row its own GROUP BY ("URLHash",
    // "EventDate") group.
    for local in 0..Q41_BLOCK_ROWS {
        let i = next;
        next += 1;
        cols.watch_id
            .push((seed ^ 0x9E37_79B9_7F4A_7C15_u64).wrapping_add(i as u64) as i64);
        cols.user_id.push(rng.random::<i64>());
        cols.url_hash.push(10_000_000_000_i64 + local as i64);
        cols.referer_hash.push(Q41_REFERER_HASH);
        cols.counter_id.push(62);
        cols.region_id.push(1 + rng.random_range(0..300));
        cols.client_ip.push(rng.random_range(0..(i32::MAX / 2)));
        cols.adv_engine_id.push(if rng.random_bool(0.1) {
            rng.random_range(1..20)
        } else {
            0
        });
        cols.resolution_width.push(rng.random_range(800..=2560));
        cols.mobile_phone.push(rng.random_range(0..=10));
        cols.search_engine_id.push(rng.random_range(0..=5));
        cols.trafic_source_id.push(-1);
        cols.is_refresh.push(0);
        cols.is_link.push(i16::from(rng.random_bool(0.05)));
        cols.is_download.push(i16::from(rng.random_bool(0.05)));
        cols.dont_count_hits.push(i16::from(rng.random_bool(0.1)));
        cols.window_client_width.push(rng.random_range(0..=2000));
        cols.window_client_height.push(rng.random_range(0..=2000));
        let day_start = i64::from(EVENT_DATE_MIN) * 86_400;
        cols.event_time
            .push(day_start + rng.random_range(0..86_400i64));
        cols.event_date.push(EVENT_DATE_MIN);
        cols.url
            .push(format!("http://example.com/q41/{local}").into_bytes());
        cols.title.push(Vec::new());
        cols.referer.push(Vec::new());
        cols.search_phrase.push(Vec::new());
        cols.mobile_phone_model.push(Vec::new());
    }

    // Q42: CounterID=62, EventDate in range, IsRefresh=0, DontCountHits=0,
    // URLHash = Q42_URL_HASH; `local % 2001` / `local / 2001` is a bijection
    // from `0..Q42_BLOCK_ROWS` onto distinct (WindowClientWidth,
    // WindowClientHeight) pairs (both columns range 0..=2000), since
    // Q42_BLOCK_ROWS < 2001 * 6, so every row is its own GROUP BY
    // ("WindowClientWidth", "WindowClientHeight") group.
    for local in 0..Q42_BLOCK_ROWS {
        let i = next;
        next += 1;
        cols.watch_id
            .push((seed ^ 0x9E37_79B9_7F4A_7C15_u64).wrapping_add(i as u64) as i64);
        cols.user_id.push(rng.random::<i64>());
        cols.url_hash.push(Q42_URL_HASH);
        cols.referer_hash.push(rng.random::<i64>());
        cols.counter_id.push(62);
        cols.region_id.push(1 + rng.random_range(0..300));
        cols.client_ip.push(rng.random_range(0..(i32::MAX / 2)));
        cols.adv_engine_id.push(if rng.random_bool(0.1) {
            rng.random_range(1..20)
        } else {
            0
        });
        cols.resolution_width.push(rng.random_range(800..=2560));
        cols.mobile_phone.push(rng.random_range(0..=10));
        cols.search_engine_id.push(rng.random_range(0..=5));
        cols.trafic_source_id.push(rng.random_range(-1..=9));
        cols.is_refresh.push(0);
        cols.is_link.push(i16::from(rng.random_bool(0.05)));
        cols.is_download.push(i16::from(rng.random_bool(0.05)));
        cols.dont_count_hits.push(0);
        cols.window_client_width.push((local % 2001) as i16);
        cols.window_client_height.push((local / 2001) as i16);
        let day_start = i64::from(EVENT_DATE_MIN) * 86_400;
        cols.event_time
            .push(day_start + rng.random_range(0..86_400i64));
        cols.event_date.push(EVENT_DATE_MIN);
        cols.url
            .push(format!("http://example.com/q42/{local}").into_bytes());
        cols.title.push(Vec::new());
        cols.referer.push(Vec::new());
        cols.search_phrase.push(Vec::new());
        cols.mobile_phone_model.push(Vec::new());
    }

    // Q43: CounterID=62, EventDate=Q43_EVENT_DATE, IsRefresh=0,
    // DontCountHits=0; one EventTime per minute within the single day
    // (Q43_BLOCK_ROWS=1,010 minutes fits in the day's 1,440) makes every row
    // its own GROUP BY DATE_TRUNC('minute', "EventTime") group.
    for local in 0..Q43_BLOCK_ROWS {
        let i = next;
        next += 1;
        cols.watch_id
            .push((seed ^ 0x9E37_79B9_7F4A_7C15_u64).wrapping_add(i as u64) as i64);
        cols.user_id.push(rng.random::<i64>());
        cols.url_hash.push(rng.random::<i64>());
        cols.referer_hash.push(rng.random::<i64>());
        cols.counter_id.push(62);
        cols.region_id.push(1 + rng.random_range(0..300));
        cols.client_ip.push(rng.random_range(0..(i32::MAX / 2)));
        cols.adv_engine_id.push(if rng.random_bool(0.1) {
            rng.random_range(1..20)
        } else {
            0
        });
        cols.resolution_width.push(rng.random_range(800..=2560));
        cols.mobile_phone.push(rng.random_range(0..=10));
        cols.search_engine_id.push(rng.random_range(0..=5));
        cols.trafic_source_id.push(rng.random_range(-1..=9));
        cols.is_refresh.push(0);
        cols.is_link.push(i16::from(rng.random_bool(0.05)));
        cols.is_download.push(i16::from(rng.random_bool(0.05)));
        cols.dont_count_hits.push(0);
        cols.window_client_width.push(rng.random_range(0..=2000));
        cols.window_client_height.push(rng.random_range(0..=2000));
        let day_start = i64::from(Q43_EVENT_DATE) * 86_400;
        cols.event_time.push(day_start + (local as i64) * 60);
        cols.event_date.push(Q43_EVENT_DATE);
        cols.url
            .push(format!("http://example.com/q43/{local}").into_bytes());
        cols.title.push(Vec::new());
        cols.referer.push(Vec::new());
        cols.search_phrase.push(Vec::new());
        cols.mobile_phone_model.push(Vec::new());
    }

    cols
}

fn write_batch(path: &Path, schema: &SchemaRef, batch: &RecordBatch) -> Result<(), FixtureError> {
    let file = File::create(path).map_err(|source| FixtureError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    let mut writer = ArrowWriter::try_new(file, schema.clone(), None).map_err(|source| {
        FixtureError::Parquet {
            path: path.to_path_buf(),
            source,
        }
    })?;
    writer
        .write(batch)
        .map_err(|source| FixtureError::Parquet {
            path: path.to_path_buf(),
            source,
        })?;
    writer.close().map_err(|source| FixtureError::Parquet {
        path: path.to_path_buf(),
        source,
    })?;
    Ok(())
}

/// Writes `hits_0.parquet`..`hits_3.parquet` ([`ROWS_PER_PART`] rows each)
/// and `hits.parquet` (the same [`TOTAL_ROWS`] rows combined) into `dir`,
/// generated deterministically from `seed`: the same `(dir, seed)` always
/// produces byte-identical files.
pub fn write_hits(dir: &Path, seed: u64) -> Result<(), FixtureError> {
    let cols = generate(seed);
    let schema = schema();

    for part in 0..PART_COUNT {
        let start = part * ROWS_PER_PART;
        let end = start + ROWS_PER_PART;
        let batch = cols.batch(&schema, start, end)?;
        write_batch(&dir.join(format!("hits_{part}.parquet")), &schema, &batch)?;
    }

    let combined = cols.batch(&schema, 0, TOTAL_ROWS)?;
    write_batch(&dir.join("hits.parquet"), &schema, &combined)?;
    Ok(())
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used)]
mod tests {
    use super::*;
    use datafusion::arrow::array::Array;
    use parquet::arrow::arrow_reader::ParquetRecordBatchReaderBuilder;
    use std::collections::HashSet;

    fn read_all(path: &Path) -> Vec<RecordBatch> {
        let file = File::open(path).expect("open parquet file");
        let reader = ParquetRecordBatchReaderBuilder::try_new(file)
            .expect("build reader")
            .build()
            .expect("construct reader");
        reader.map(|b| b.expect("read batch")).collect::<Vec<_>>()
    }

    fn row_count(batches: &[RecordBatch]) -> usize {
        batches.iter().map(RecordBatch::num_rows).sum()
    }

    /// Every column `write_hits` plants is one of the 25 distinct quoted
    /// identifiers upstream's `queries.sql` actually references, and every
    /// such identifier is planted: neither side carries a column the other
    /// doesn't name.
    #[test]
    fn queries_sql_references_every_column() {
        let queries_sql = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../benchmarks/clickbench/parquet/queries.sql"
        ));
        let referenced: HashSet<String> = queries_sql
            .split('"')
            .skip(1)
            .step_by(2)
            .map(str::to_string)
            .collect();
        let planted: HashSet<String> = schema().fields().iter().map(|f| f.name().clone()).collect();
        assert_eq!(referenced, planted);
        assert_eq!(planted.len(), 25);
    }

    #[test]
    fn write_hits_creates_all_five_files() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        for part in 0..PART_COUNT {
            assert!(dir.path().join(format!("hits_{part}.parquet")).is_file());
        }
        assert!(dir.path().join("hits.parquet").is_file());
    }

    #[test]
    fn row_counts_match_spec() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        for part in 0..PART_COUNT {
            let batches = read_all(&dir.path().join(format!("hits_{part}.parquet")));
            assert_eq!(row_count(&batches), ROWS_PER_PART);
        }
        let combined = read_all(&dir.path().join("hits.parquet"));
        assert_eq!(row_count(&combined), TOTAL_ROWS);
    }

    /// The 5 string-shaped columns round-trip as `Binary`, never `Utf8`: the
    /// fixture carries no string annotation, matching `suite.toml`'s
    /// `binary_as_string` table option, which only has an effect when the
    /// Parquet column itself is unannotated binary.
    #[test]
    fn string_columns_carry_no_utf8_annotation() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let schema = combined[0].schema();
        for name in [
            "URL",
            "Title",
            "Referer",
            "SearchPhrase",
            "MobilePhoneModel",
        ] {
            let field = schema.field_with_name(name).expect("field present");
            assert_eq!(
                field.data_type(),
                &DataType::Binary,
                "{name} must be Binary"
            );
        }
    }

    /// `hits.parquet` holds exactly the same rows as the four parts
    /// concatenated, column by column: a caller that mounts either shape
    /// under `suite.toml`'s table template reads the same data.
    #[test]
    fn combined_file_equals_concatenated_parts() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 11).expect("write_hits");

        let combined = read_all(&dir.path().join("hits.parquet"));
        let combined_watch_id: Vec<i64> = combined
            .iter()
            .flat_map(|b| {
                b.column_by_name("WatchID")
                    .expect("WatchID column")
                    .as_any()
                    .downcast_ref::<Int64Array>()
                    .expect("Int64Array")
                    .values()
                    .to_vec()
            })
            .collect();

        let mut parts_watch_id: Vec<i64> = Vec::new();
        for part in 0..PART_COUNT {
            let batches = read_all(&dir.path().join(format!("hits_{part}.parquet")));
            for batch in &batches {
                parts_watch_id.extend(
                    batch
                        .column_by_name("WatchID")
                        .expect("WatchID column")
                        .as_any()
                        .downcast_ref::<Int64Array>()
                        .expect("Int64Array")
                        .values(),
                );
            }
        }

        assert_eq!(combined_watch_id, parts_watch_id);
        assert_eq!(combined_watch_id.len(), TOTAL_ROWS);
    }

    /// Two runs with the same seed produce byte-identical files: nothing in
    /// generation reads wall-clock time, ambient randomness, or iteration
    /// order over an unordered collection.
    #[test]
    fn same_seed_is_byte_identical() {
        let dir_a = tempfile::tempdir().expect("tempdir a");
        let dir_b = tempfile::tempdir().expect("tempdir b");
        write_hits(dir_a.path(), 42).expect("write_hits a");
        write_hits(dir_b.path(), 42).expect("write_hits b");

        for name in [
            "hits_0.parquet",
            "hits_1.parquet",
            "hits_2.parquet",
            "hits_3.parquet",
            "hits.parquet",
        ] {
            let bytes_a = std::fs::read(dir_a.path().join(name)).expect("read a");
            let bytes_b = std::fs::read(dir_b.path().join(name)).expect("read b");
            assert_eq!(bytes_a, bytes_b, "{name} differs between same-seed runs");
        }
    }

    /// A different seed changes the output: the generator is seed-sensitive,
    /// not merely index-sensitive.
    #[test]
    fn different_seed_changes_output() {
        let dir_a = tempfile::tempdir().expect("tempdir a");
        let dir_b = tempfile::tempdir().expect("tempdir b");
        write_hits(dir_a.path(), 1).expect("write_hits a");
        write_hits(dir_b.path(), 2).expect("write_hits b");

        let bytes_a = std::fs::read(dir_a.path().join("hits.parquet")).expect("read a");
        let bytes_b = std::fs::read(dir_b.path().join("hits.parquet")).expect("read b");
        assert_ne!(bytes_a, bytes_b);
    }

    /// Q20's literal (`"UserID" = 435090932899640449`) is present, on row 0
    /// as planted.
    #[test]
    fn q20_user_id_literal_is_planted() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let user_id = combined[0]
            .column_by_name("UserID")
            .expect("UserID column")
            .as_any()
            .downcast_ref::<Int64Array>()
            .expect("Int64Array");
        assert_eq!(user_id.value(0), Q20_USER_ID);
    }

    /// Q41's literal (`"RefererHash" = 3594120000172545465`) and its
    /// co-occurring filters (`"CounterID" = 62`, `"EventDate"` in range,
    /// `"IsRefresh" = 0`, `"TraficSourceID" IN (-1, 6)`) are all planted
    /// together on row 2. On its own this is not enough for Q41 to return
    /// rows past its `OFFSET 100`: that needs at least 101 distinct
    /// `("URLHash", "EventDate")` groups, which is what the `Q41_BLOCK_ROWS`
    /// rows planted in `generate` are for (see
    /// `q41_block_has_enough_groups_past_offset` below).
    #[test]
    fn q41_referer_hash_literal_is_planted_with_its_filters() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let batch = &combined[0];
        let col = |name: &str| {
            batch
                .column_by_name(name)
                .unwrap_or_else(|| panic!("{name} column"))
        };
        assert_eq!(
            col("RefererHash")
                .as_any()
                .downcast_ref::<Int64Array>()
                .expect("Int64Array")
                .value(2),
            Q41_REFERER_HASH
        );
        assert_eq!(
            col("CounterID")
                .as_any()
                .downcast_ref::<Int32Array>()
                .expect("Int32Array")
                .value(2),
            62
        );
        let event_date = col("EventDate")
            .as_any()
            .downcast_ref::<UInt16Array>()
            .expect("UInt16Array")
            .value(2);
        assert!((EVENT_DATE_MIN..=EVENT_DATE_MAX).contains(&event_date));
        assert_eq!(
            col("IsRefresh")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array")
                .value(2),
            0
        );
        let trafic_source_id = col("TraficSourceID")
            .as_any()
            .downcast_ref::<Int16Array>()
            .expect("Int16Array")
            .value(2);
        assert!(trafic_source_id == -1 || trafic_source_id == 6);
    }

    /// `EventDate` spans the full upstream range (`'2013-07-01'..'2013-07-31'`,
    /// days 15887..15917): both endpoints occur somewhere in the fixture.
    #[test]
    fn event_date_spans_the_full_upstream_range() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let values: HashSet<u16> = combined
            .iter()
            .flat_map(|b| {
                b.column_by_name("EventDate")
                    .expect("EventDate column")
                    .as_any()
                    .downcast_ref::<UInt16Array>()
                    .expect("UInt16Array")
                    .values()
                    .to_vec()
            })
            .collect();
        assert!(values.contains(&EVENT_DATE_MIN));
        assert!(values.contains(&EVENT_DATE_MAX));
        for v in &values {
            assert!((EVENT_DATE_MIN..=EVENT_DATE_MAX).contains(v));
        }
    }

    /// `SearchPhrase` carries exactly [`SEARCH_PHRASES`]`.len()` distinct
    /// non-empty values, in as-equal-as-possible counts (every count within
    /// 1 of every other), so Q6's `COUNT(DISTINCT "SearchPhrase")` and
    /// Q13-19's grouping have a known, reproducible shape.
    #[test]
    fn search_phrase_pool_is_equal_count() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));

        let mut counts: std::collections::HashMap<Vec<u8>, usize> =
            std::collections::HashMap::new();
        for batch in &combined {
            let col = batch
                .column_by_name("SearchPhrase")
                .expect("SearchPhrase column")
                .as_any()
                .downcast_ref::<BinaryArray>()
                .expect("BinaryArray");
            for i in 0..col.len() {
                let value = col.value(i).to_vec();
                if !value.is_empty() {
                    *counts.entry(value).or_insert(0) += 1;
                }
            }
        }

        assert_eq!(counts.len(), SEARCH_PHRASES.len());
        let min = *counts.values().min().expect("at least one phrase");
        let max = *counts.values().max().expect("at least one phrase");
        assert!(
            max - min <= 1,
            "counts must be within 1 of each other: {counts:?}"
        );
    }

    /// Q21-24's `"URL" LIKE '%google%'` and Q23's `"Title" LIKE '%Google%'`
    /// each match at least one planted row.
    #[test]
    fn google_substrings_are_planted() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));

        let mut url_has_google = false;
        let mut title_has_google = false;
        for batch in &combined {
            let url = batch
                .column_by_name("URL")
                .expect("URL column")
                .as_any()
                .downcast_ref::<BinaryArray>()
                .expect("BinaryArray");
            let title = batch
                .column_by_name("Title")
                .expect("Title column")
                .as_any()
                .downcast_ref::<BinaryArray>()
                .expect("BinaryArray");
            for i in 0..url.len() {
                if String::from_utf8_lossy(url.value(i)).contains("google") {
                    url_has_google = true;
                }
                if String::from_utf8_lossy(title.value(i)).contains("Google") {
                    title_has_google = true;
                }
            }
        }
        assert!(url_has_google, "no URL contains \"google\"");
        assert!(title_has_google, "no Title contains \"Google\"");
    }

    /// Pulls the columns a Q39/Q41/Q42/Q43-shaped predicate needs into
    /// per-row tuples, for computing group counts in plain Rust the same
    /// way the statement's `WHERE`/`GROUP BY` would.
    struct Row {
        counter_id: i32,
        event_date: u16,
        is_refresh: i16,
        is_link: i16,
        is_download: i16,
        dont_count_hits: i16,
        trafic_source_id: i16,
        search_engine_id: i16,
        adv_engine_id: i16,
        url_hash: i64,
        referer_hash: i64,
        window_client_width: i16,
        window_client_height: i16,
        event_time: i64,
        url: Vec<u8>,
        referer: Vec<u8>,
    }

    fn all_rows(batches: &[RecordBatch]) -> Vec<Row> {
        let mut rows = Vec::new();
        for batch in batches {
            let counter_id = batch
                .column_by_name("CounterID")
                .expect("CounterID column")
                .as_any()
                .downcast_ref::<Int32Array>()
                .expect("Int32Array");
            let event_date = batch
                .column_by_name("EventDate")
                .expect("EventDate column")
                .as_any()
                .downcast_ref::<UInt16Array>()
                .expect("UInt16Array");
            let is_refresh = batch
                .column_by_name("IsRefresh")
                .expect("IsRefresh column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let is_link = batch
                .column_by_name("IsLink")
                .expect("IsLink column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let is_download = batch
                .column_by_name("IsDownload")
                .expect("IsDownload column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let dont_count_hits = batch
                .column_by_name("DontCountHits")
                .expect("DontCountHits column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let trafic_source_id = batch
                .column_by_name("TraficSourceID")
                .expect("TraficSourceID column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let search_engine_id = batch
                .column_by_name("SearchEngineID")
                .expect("SearchEngineID column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let adv_engine_id = batch
                .column_by_name("AdvEngineID")
                .expect("AdvEngineID column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let url_hash = batch
                .column_by_name("URLHash")
                .expect("URLHash column")
                .as_any()
                .downcast_ref::<Int64Array>()
                .expect("Int64Array");
            let referer_hash = batch
                .column_by_name("RefererHash")
                .expect("RefererHash column")
                .as_any()
                .downcast_ref::<Int64Array>()
                .expect("Int64Array");
            let window_client_width = batch
                .column_by_name("WindowClientWidth")
                .expect("WindowClientWidth column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let window_client_height = batch
                .column_by_name("WindowClientHeight")
                .expect("WindowClientHeight column")
                .as_any()
                .downcast_ref::<Int16Array>()
                .expect("Int16Array");
            let event_time = batch
                .column_by_name("EventTime")
                .expect("EventTime column")
                .as_any()
                .downcast_ref::<Int64Array>()
                .expect("Int64Array");
            let url = batch
                .column_by_name("URL")
                .expect("URL column")
                .as_any()
                .downcast_ref::<BinaryArray>()
                .expect("BinaryArray");
            let referer = batch
                .column_by_name("Referer")
                .expect("Referer column")
                .as_any()
                .downcast_ref::<BinaryArray>()
                .expect("BinaryArray");

            for i in 0..batch.num_rows() {
                rows.push(Row {
                    counter_id: counter_id.value(i),
                    event_date: event_date.value(i),
                    is_refresh: is_refresh.value(i),
                    is_link: is_link.value(i),
                    is_download: is_download.value(i),
                    dont_count_hits: dont_count_hits.value(i),
                    trafic_source_id: trafic_source_id.value(i),
                    search_engine_id: search_engine_id.value(i),
                    adv_engine_id: adv_engine_id.value(i),
                    url_hash: url_hash.value(i),
                    referer_hash: referer_hash.value(i),
                    window_client_width: window_client_width.value(i),
                    window_client_height: window_client_height.value(i),
                    event_time: event_time.value(i),
                    url: url.value(i).to_vec(),
                    referer: referer.value(i).to_vec(),
                });
            }
        }
        rows
    }

    /// Required test, distinguishing: red against the pre-block fixture
    /// (only the ~114-row random chance of matching Q39's predicate, well
    /// under 1,010 distinct `URL` groups), green once `Q39_BLOCK_ROWS` rows
    /// are planted. Q39's `GROUP BY "URL" ... LIMIT 10 OFFSET 1000` returns
    /// 10 rows only when the WHERE-matching set has at least 1,010 (OFFSET +
    /// LIMIT) distinct `URL` values.
    #[test]
    fn q39_block_has_enough_groups_past_offset() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let rows = all_rows(&combined);

        let groups: HashSet<Vec<u8>> = rows
            .iter()
            .filter(|r| {
                r.counter_id == 62
                    && (EVENT_DATE_MIN..=EVENT_DATE_MAX).contains(&r.event_date)
                    && r.is_refresh == 0
                    && r.is_link != 0
                    && r.is_download == 0
            })
            .map(|r| r.url.clone())
            .collect();
        assert!(
            groups.len() >= 1_010,
            "Q39 needs at least 1,010 distinct URL groups (OFFSET 1000 + LIMIT 10), got {}",
            groups.len()
        );
    }

    /// Group key for [`q40_block_has_enough_groups_past_offset`]:
    /// `(TraficSourceID, SearchEngineID, AdvEngineID, Src, Dst)`.
    type Q40GroupKey = (i16, i16, i16, Vec<u8>, Vec<u8>);

    /// Required test: Q40's `GROUP BY "TraficSourceID", "SearchEngineID",
    /// "AdvEngineID", Src, Dst ... LIMIT 10 OFFSET 1000` returns 10 rows only
    /// when the WHERE-matching set (`CounterID = 62 AND EventDate` in range
    /// `AND IsRefresh = 0`, no further restriction) has at least 1,010
    /// (OFFSET + LIMIT) distinct groups. Unlike Q39/Q41/Q42/Q43 this needs no
    /// planted block: `Src` (`CASE WHEN ("SearchEngineID" = 0 AND
    /// "AdvEngineID" = 0) THEN "Referer" ELSE ''`) and `Dst` (`"URL"`) already
    /// vary enough across the random base rows that match the `WHERE` (see
    /// the module doc comment above).
    #[test]
    fn q40_block_has_enough_groups_past_offset() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let rows = all_rows(&combined);

        let groups: HashSet<Q40GroupKey> = rows
            .iter()
            .filter(|r| {
                r.counter_id == 62
                    && (EVENT_DATE_MIN..=EVENT_DATE_MAX).contains(&r.event_date)
                    && r.is_refresh == 0
            })
            .map(|r| {
                let src = if r.search_engine_id == 0 && r.adv_engine_id == 0 {
                    r.referer.clone()
                } else {
                    Vec::new()
                };
                (
                    r.trafic_source_id,
                    r.search_engine_id,
                    r.adv_engine_id,
                    src,
                    r.url.clone(),
                )
            })
            .collect();
        assert!(
            groups.len() >= 1_010,
            "Q40 needs at least 1,010 distinct (TraficSourceID, SearchEngineID, AdvEngineID, Src, Dst) groups (OFFSET 1000 + LIMIT 10), got {}",
            groups.len()
        );
    }

    /// Required test, distinguishing: red against the pre-block fixture
    /// (on the order of 10 rows match Q41's predicate by random chance,
    /// well under 110 distinct groups), green once `Q41_BLOCK_ROWS` rows are
    /// planted. Q41's `GROUP BY "URLHash", "EventDate" ... LIMIT 10 OFFSET
    /// 100` returns 10 rows only when the WHERE-matching set has at least
    /// 110 (OFFSET + LIMIT) distinct `(URLHash, EventDate)` pairs.
    #[test]
    fn q41_block_has_enough_groups_past_offset() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let rows = all_rows(&combined);

        let groups: HashSet<(i64, u16)> = rows
            .iter()
            .filter(|r| {
                r.counter_id == 62
                    && (EVENT_DATE_MIN..=EVENT_DATE_MAX).contains(&r.event_date)
                    && r.is_refresh == 0
                    && (r.trafic_source_id == -1 || r.trafic_source_id == 6)
                    && r.referer_hash == Q41_REFERER_HASH
            })
            .map(|r| (r.url_hash, r.event_date))
            .collect();
        assert!(
            groups.len() >= 110,
            "Q41 needs at least 110 distinct (URLHash, EventDate) groups (OFFSET 100 + LIMIT 10), got {}",
            groups.len()
        );
    }

    /// Required test, distinguishing: red against the pre-block fixture (on
    /// the order of 50 rows match Q42's predicate by random chance, well
    /// under 10,010 distinct groups), green once `Q42_BLOCK_ROWS` rows are
    /// planted. Q42's `GROUP BY "WindowClientWidth", "WindowClientHeight"
    /// ... LIMIT 10 OFFSET 10000` returns 10 rows only when the
    /// WHERE-matching set has at least 10,010 (OFFSET + LIMIT) distinct
    /// `(WindowClientWidth, WindowClientHeight)` pairs.
    #[test]
    fn q42_block_has_enough_groups_past_offset() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let rows = all_rows(&combined);

        let groups: HashSet<(i16, i16)> = rows
            .iter()
            .filter(|r| {
                r.counter_id == 62
                    && (EVENT_DATE_MIN..=EVENT_DATE_MAX).contains(&r.event_date)
                    && r.is_refresh == 0
                    && r.dont_count_hits == 0
                    && r.url_hash == Q42_URL_HASH
            })
            .map(|r| (r.window_client_width, r.window_client_height))
            .collect();
        assert!(
            groups.len() >= 10_010,
            "Q42 needs at least 10,010 distinct (WindowClientWidth, WindowClientHeight) groups (OFFSET 10000 + LIMIT 10), got {}",
            groups.len()
        );
    }

    /// Required test, distinguishing: red against the pre-block fixture (on
    /// the order of 130 rows match Q43's predicate by random chance, well
    /// under 1,010 distinct minute buckets), green once `Q43_BLOCK_ROWS`
    /// rows are planted. Q43's `GROUP BY DATE_TRUNC('minute', "EventTime")
    /// ... LIMIT 10 OFFSET 1000` returns 10 rows only when the
    /// WHERE-matching set has at least 1,010 (OFFSET + LIMIT) distinct
    /// truncated-to-the-minute `EventTime` values. Q43's own `WHERE` is
    /// `"EventDate" >= '2013-07-14' AND "EventDate" <= '2013-07-15'`
    /// (`queries.sql` line 43): `Q43_EVENT_DATE` is the first of those two
    /// days, so the second is `Q43_EVENT_DATE + 1`, not `- 1`.
    #[test]
    fn q43_block_has_enough_groups_past_offset() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));
        let rows = all_rows(&combined);

        let groups: HashSet<i64> = rows
            .iter()
            .filter(|r| {
                r.counter_id == 62
                    && (r.event_date == Q43_EVENT_DATE || r.event_date == Q43_EVENT_DATE + 1)
                    && r.is_refresh == 0
                    && r.dont_count_hits == 0
            })
            .map(|r| r.event_time.div_euclid(60))
            .collect();
        assert!(
            groups.len() >= 1_010,
            "Q43 needs at least 1,010 distinct minute-truncated EventTime groups (OFFSET 1000 + LIMIT 10), got {}",
            groups.len()
        );
    }

    /// Required test: Q26 (`ORDER BY "SearchPhrase" LIMIT 10`) cuts inside a
    /// run of equal values, exercising the comparator's ORDER BY+LIMIT
    /// boundary-tie handling (ADR-2040 D7): the alphabetically smallest
    /// non-empty `SearchPhrase` has at least 10 rows.
    #[test]
    fn q26_alphabetically_smallest_search_phrase_has_tie_past_limit() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 7).expect("write_hits");
        let combined = read_all(&dir.path().join("hits.parquet"));

        let smallest = SEARCH_PHRASES.iter().min().expect("at least one phrase");
        let mut count = 0usize;
        for batch in &combined {
            let col = batch
                .column_by_name("SearchPhrase")
                .expect("SearchPhrase column")
                .as_any()
                .downcast_ref::<BinaryArray>()
                .expect("BinaryArray");
            for i in 0..col.len() {
                if col.value(i) == smallest.as_bytes() {
                    count += 1;
                }
            }
        }
        assert!(
            count >= 10,
            "alphabetically smallest SearchPhrase {smallest:?} has only {count} rows, need >= 10"
        );
    }

    /// Required test: writing the same seed into the same directory twice
    /// overwrites in place rather than corrupting or appending (`write_batch`
    /// uses `File::create`, which truncates).
    #[test]
    fn same_seed_overwrite_in_place_is_byte_identical() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_hits(dir.path(), 99).expect("write_hits first");

        let names = [
            "hits_0.parquet",
            "hits_1.parquet",
            "hits_2.parquet",
            "hits_3.parquet",
            "hits.parquet",
        ];
        let before: Vec<Vec<u8>> = names
            .iter()
            .map(|name| std::fs::read(dir.path().join(name)).expect("read before"))
            .collect();

        write_hits(dir.path(), 99).expect("write_hits second");

        for (name, bytes_before) in names.iter().zip(before) {
            let bytes_after = std::fs::read(dir.path().join(name)).expect("read after");
            assert_eq!(
                bytes_before, bytes_after,
                "{name} differs after overwrite in place"
            );
        }
    }
}
