//! Generated protobuf types for persistent metadata. The .proto files under
//! `proto/ravel/` are the source of truth; field numbers are frozen.
//!
//! These types are generated by prost, which skips unknown fields on decode
//! but does not store them. Decoding a message written by a newer writer
//! succeeds, and re-encoding the decoded value drops every field the current
//! schema does not name. Callers that rewrite a stored footer, commit record,
//! or catalog object must build the new value explicitly instead of
//! round-tripping a decoded one. Making these types retain unknown fields
//! would be a format-change decision requiring an ADR.

pub mod segment {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.segment.v1.rs"));
    }
}

pub mod commit {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.commit.v1.rs"));
    }
}

pub mod catalog {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.catalog.v1.rs"));
    }
}

pub mod logseg {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.logseg.v1.rs"));
    }
}
