//! Generated protobuf types for persistent metadata. The .proto files under
//! `proto/ravel/` are the source of truth; field numbers are frozen.
//!
//! These types are generated by prost, which skips unknown fields on decode
//! but does not store them. Decoding a message written by a newer writer
//! succeeds, and re-encoding the decoded value drops every field the current
//! schema does not name. Callers that rewrite a stored footer, commit record,
//! or catalog object must build the new value explicitly instead of
//! round-tripping a decoded one. Making these types retain unknown fields
//! would be a format-change decision requiring an ADR.

pub mod segment {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.segment.v1.rs"));
    }
}

pub mod commit {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.commit.v1.rs"));
    }
}

pub mod catalog {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.catalog.v1.rs"));
    }
}

pub mod logseg {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.logseg.v1.rs"));
    }
}

pub mod sys {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.sys.v1.rs"));
    }
}

/// Distributed read fan-out fragment protocol (ADR-0071). Unlike every other
/// module here, this is a TRANSIENT wire contract between query processes, not
/// a persistent stored format: no byte defined here is ever written to object
/// storage. It is versioned via `FetchRequest.protocol_version`; field numbers
/// are frozen once merged.
pub mod queryfrag {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/ravel.queryfrag.v1.rs"));
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod queryfrag_tests {
    //! Round-trip of the ADR-0071 fragment response, proving f64 value bits and
    //! zig-zag timestamp deltas survive encode/decode byte-for-byte. Every
    //! assertion compares u64 bit patterns, never f64 values, so NaN payloads
    //! and -0.0 are compared exactly (the storage/dedup float-comparison rule).

    use prost::Message;

    use super::queryfrag::v1::{FetchResponse, Label, Run, SeriesFrame, fetch_response::Frame};

    /// A series frame carrying pathological value bits and negative timestamp
    /// deltas round-trips with every value bit and delta preserved exactly.
    #[test]
    fn series_frame_preserves_value_bits_and_negative_deltas() {
        // The NaN staleness marker (0x7ff0000000000002), quiet/signaling NaNs
        // with distinct payloads, -0.0, +0.0, and ordinary values. Comparing
        // these as f64 would collapse every NaN and equate -0.0 with +0.0; the
        // wire contract must keep them distinct as bit patterns.
        let value_bits: Vec<u64> = vec![
            0x7ff0_0000_0000_0002, // staleness marker
            0x7ff8_0000_0000_0001, // quiet NaN, payload 1
            0xfff0_0000_0000_000a, // signaling NaN, sign set, payload 0xa
            0x8000_0000_0000_0000, // -0.0
            0x0000_0000_0000_0000, // +0.0
            f64::to_bits(1.5),
            f64::to_bits(-2.25),
        ];
        // Zig-zag deltas including negatives and the i64 extremes.
        let ts_delta: Vec<i64> = vec![0, -1, 1, -1_000_000, i64::MIN, i64::MAX];

        let frame = SeriesFrame {
            series_id: vec![7u8; 16],
            labels: vec![Label {
                name: "__name__".to_string(),
                value: "up".to_string(),
            }],
            runs: vec![Run {
                created_unix_ns: -42,
                writer_epoch: 3,
                writer_seq: 9,
                ts_delta: ts_delta.clone(),
                value_bits: value_bits.clone(),
            }],
        };
        let response = FetchResponse {
            frame: Some(Frame::Series(frame)),
        };

        let encoded = response.encode_to_vec();
        let decoded = FetchResponse::decode(encoded.as_slice()).expect("decode");

        let Some(Frame::Series(series)) = decoded.frame else {
            panic!("expected a series frame");
        };
        assert_eq!(series.series_id, vec![7u8; 16]);
        assert_eq!(series.runs.len(), 1);
        let run = &series.runs[0];
        assert_eq!(run.created_unix_ns, -42);
        assert_eq!(run.writer_epoch, 3);
        assert_eq!(run.writer_seq, 9);
        assert_eq!(
            run.ts_delta, ts_delta,
            "negative and extreme deltas survive"
        );

        // Bit-for-bit comparison as u64; never f64 equality (NaN != NaN and
        // -0.0 == 0.0 would both give wrong answers here).
        assert_eq!(run.value_bits.len(), value_bits.len());
        for (got, want) in run.value_bits.iter().zip(value_bits.iter()) {
            assert_eq!(got, want, "value bit pattern must survive exactly");
        }
        // The staleness marker specifically survived.
        assert_eq!(run.value_bits[0], 0x7ff0_0000_0000_0002);
        // -0.0 stayed distinct from +0.0 at the bit level.
        assert_eq!(run.value_bits[3], 0x8000_0000_0000_0000);
        assert_ne!(run.value_bits[3], run.value_bits[4]);
    }
}
