//! Columnar row blocks (docs/log-segment-format.md "BLOCKS").
//!
//! A block holds a run of records column by column: a header of page
//! descriptors, then the pages. A column present in only some rows of the
//! block carries a presence bitmap page (`enc = Bitmap`) immediately before its
//! value page, so decode restores exact row alignment; a column absent from
//! every row of the block occupies zero bytes. The block's crc32c lives in its
//! SKIP_IDX level-0 entry, not inline; [`read_block`] verifies it before
//! decoding anything.

use std::cell::Cell;
use std::collections::HashMap;
use std::hash::{BuildHasherDefault, Hasher};

use crate::encoding::{
    DecodedStrings, Enc, decode_bitmap, decode_f64, decode_fixed, decode_i64,
    decode_strings_columnar, encode_bitmap, encode_f64, encode_fixed, encode_i64, encode_strings,
    encode_strings_dict,
};
use crate::error::LogSegError;
use crate::page::{PageDesc, read_page, write_page};
use crate::record::{
    COL_ATTRS_RAW, COL_BODY, COL_FLAGS, COL_OBSERVED_TS, COL_SEVERITY_NUM, COL_SEVERITY_TEXT,
    COL_SPAN_ID, COL_STREAM_REF, COL_TRACE_ID, COL_TS, ColumnValue, FieldType, ResolvedRow,
    SPAN_ID_WIDTH, TRACE_ID_WIDTH,
};
use crate::varint::{get_uvarint, put_uvarint};

/// Upper bound on a block's decoded record count (untrusted-input guard). A
/// real block never approaches this; it caps allocation from a hostile header.
const MAX_RECORDS: u64 = 1 << 24;
/// Upper bound on a block's page count. Fixed columns plus the 1000-column
/// dynamic budget, each up to two pages, stays well under this. PAGE_DIR
/// derives its own per-group caps from this (ADR-0699 decision 2).
pub const MAX_PAGES: u64 = 4096;

/// Cap on a decoded page's `column_id`, matching the field-directory cap
/// [`crate::reader::MAX_FIELDS`] that bounds how many fields an object may
/// declare.
///
/// Column ids index a dense slot vector in [`ColMap`], so the allocation is a
/// function of the LARGEST id seen, not of how many columns a block actually
/// carries. A page descriptor is read from the object, which is untrusted
/// input: without this cap a single corrupt or hostile block declaring a
/// `column_id` near `u32::MAX` would resize that vector to billions of slots
/// and exhaust memory before any pool limit could observe it.
const MAX_COLUMN_ID: u64 = 1 << 20;

/// A cheap multiplicative mix (FxHash-style) for column ids, in place of
/// std's default SipHash. Column ids are dense, small (a real schema tops out
/// around a hundred, capped at [`crate::writer::RlogConfig::max_dynamic_columns`])
/// and self-generated by this crate's own writer -- never attacker-controlled
/// -- so the membership test [`read_block_columns`] and `decode_v4_block` run
/// once per page per block has no HashDoS surface to resist, and paying
/// SipHash's cost for it is pure waste on the hottest loop in decode.
#[derive(Default)]
pub struct ColumnIdHasher(u64);

const COLUMN_ID_HASH_SEED: u64 = 0x517c_c1b7_2722_0a95;

impl Hasher for ColumnIdHasher {
    fn write(&mut self, bytes: &[u8]) {
        for &b in bytes {
            self.0 = (self.0.rotate_left(5) ^ u64::from(b)).wrapping_mul(COLUMN_ID_HASH_SEED);
        }
    }

    fn write_u32(&mut self, i: u32) {
        self.0 = (self.0.rotate_left(5) ^ u64::from(i)).wrapping_mul(COLUMN_ID_HASH_SEED);
    }

    fn finish(&self) -> u64 {
        self.0
    }
}

/// Membership set for column ids, threaded from [`crate::ColumnSelection::resolve`]
/// through to the per-page filter in [`read_block_columns`] and
/// `decode_v4_block`. Not the same type [`crate::ColumnSelection::resolve`]
/// itself returns: that method is a stable cross-crate boundary (`ravel-query`
/// resolves it directly for its ADR-0699 fetch-range planning), so it keeps
/// std's `HashSet<u32>`; the reader re-collects into this faster set for its
/// own internal, per-crate use.
pub type ColumnIdSet = std::collections::HashSet<u32, BuildHasherDefault<ColumnIdHasher>>;

/// The type of a dynamic attribute column, as resolved from FIELD_DIR. Fixed
/// columns (ids 0..=9) carry no plan; their types are implicit.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct ColumnPlan {
    pub column_id: u32,
    pub ty: FieldType,
}

/// Per-numeric-column statistics stored in the SKIP_IDX level-0 entry
/// (docs/log-segment-format.md SKIP_IDX). `min_bits`/`max_bits` hold an i64 as
/// its two's-complement `u64`, or an f64 as its `to_bits` pattern; f64 min/max
/// use `total_cmp` order over non-NaN values, and NaN values are counted in
/// `has_nan` and excluded from min/max.
///
/// Since RLOG v3 (ADR-0095) the values folded in are each row's resolved
/// merged-view value for the column's attribute name
/// ([`ResolvedRow::stat_winners`]), not the row's raw columnar occurrence. A row
/// whose resolved value for that name is of another type counts in `null_count`
/// only. That makes the bounds bound what a reader materializing a declared
/// typed column actually produces per row, which is the whole point of pruning
/// on them; the raw value page may hold a losing occurrence outside these
/// bounds, and the bounds may cover a value that lives only in STREAM_DIR
/// (a name a row resolves off its resource or scope).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct NumStat {
    pub column_id: u32,
    pub ty: FieldType,
    pub min_bits: u64,
    pub max_bits: u64,
    pub null_count: u32,
    pub has_nan: bool,
}

/// The output of encoding one block: its pages, and everything its SKIP_IDX
/// level-0 entry needs beyond a byte range.
///
/// The pages are handed back separately from any layout. Version 3 concatenated
/// a header and them into one contiguous block; version 4 spreads them across
/// its row group's column chunks (ADR-0699 decision 1), which is why nothing
/// here commits to a placement.
#[derive(Clone, Debug)]
pub struct BlockWriteOut {
    /// Page descriptors in ascending `column_id` order; a partially present
    /// column's presence bitmap page comes immediately before its value page.
    pub descs: Vec<PageDesc>,
    /// The descriptors' stored page bytes, concatenated in descriptor order.
    ///
    /// Descriptor order is staging order, which is *not* ascending `column_id`:
    /// the fixed columns are staged in field order, so `flags` (column 8) comes
    /// before `severity_text` (column 4). Version 3's block crc covers this
    /// order because it covers these bytes; version 4's covers the pages in
    /// ascending `column_id` order, which is a different concatenation of the
    /// same pages (ADR-0699 decision 2), so it is computed while the row group
    /// is placed, not from here.
    pub payload: Vec<u8>,
    pub record_count: u32,
    pub stats: Vec<NumStat>,
    pub min_ts: i64,
    pub max_ts: i64,
    pub min_stream_ref: u32,
    pub max_stream_ref: u32,
}

impl BlockWriteOut {
    /// The version-3 block bytes -- the page-descriptor header followed by the
    /// pages -- and the crc32c over the whole of them, which is what a
    /// version-3 SKIP_IDX level-0 entry carries.
    ///
    /// Version 4 does not write this layout; it is retained for the version-3
    /// reader's tests, which need a version-3 producer for arbitrary inputs
    /// (see `RlogWriter::finish_v3_for_tests`).
    pub fn v3_bytes(&self) -> (Vec<u8>, u32) {
        let mut block = Vec::with_capacity(self.payload.len() + 8 * self.descs.len());
        put_uvarint(&mut block, u64::from(self.record_count));
        put_uvarint(&mut block, self.descs.len() as u64);
        for d in &self.descs {
            put_uvarint(&mut block, u64::from(d.column_id));
            block.push(d.enc.to_u8());
            block.push(d.comp);
            put_uvarint(&mut block, d.len);
            put_uvarint(&mut block, d.uncomp_len);
        }
        block.extend_from_slice(&self.payload);
        let crc = crc32c::crc32c(&block);
        (block, crc)
    }
}

/// One page staged for a column: its encoding tag and the encoded value bytes.
struct StagedPage {
    column_id: u32,
    enc: Enc,
    bytes: Vec<u8>,
}

/// Stages a column's pages: a presence bitmap page (only when the column is
/// partially present) followed by the value page. A wholly-absent column
/// stages nothing.
fn stage_column(
    pages: &mut Vec<StagedPage>,
    column_id: u32,
    present: &[bool],
    value_enc: Enc,
    value_bytes: Vec<u8>,
) {
    let mut any = false;
    let mut all = true;
    for &p in present {
        any |= p;
        all &= p;
    }
    if !any {
        return;
    }
    if !all {
        pages.push(StagedPage {
            column_id,
            enc: Enc::Bitmap,
            bytes: encode_bitmap(present),
        });
    }
    pages.push(StagedPage {
        column_id,
        enc: value_enc,
        bytes: value_bytes,
    });
}

/// i64 min/max stat over the contributing values (two's-complement bits).
///
/// `vals` is one entry per row of the block: `Some` when the value that row
/// resolves for this column's name is an i64 (the value being the resolved one,
/// [`winner_value`]), `None` when it is of another type or the row resolves the
/// name to nothing. Every `None` counts in `null_count` (ADR-0095 decision 2).
///
/// "Resolves" spans both layers, not the record's own attributes alone: a row
/// carrying no occurrence of the name still contributes the value its resource
/// or scope carries, so a `Some` here need not correspond to anything in the
/// block's value page for the column -- and a block may get a stat for a column
/// it has no page for at all.
///
/// `f64_stat` and `bool_stat` below carry the same contract for their types.
fn i64_stat(column_id: u32, vals: &[Option<i64>]) -> NumStat {
    let mut min = i64::MAX;
    let mut max = i64::MIN;
    let mut nulls = 0u32;
    let mut any = false;
    for v in vals {
        match v {
            Some(x) => {
                any = true;
                min = min.min(*x);
                max = max.max(*x);
            }
            None => nulls = nulls.saturating_add(1),
        }
    }
    if !any {
        min = 0;
        max = 0;
    }
    NumStat {
        column_id,
        ty: FieldType::I64,
        min_bits: min as u64,
        max_bits: max as u64,
        null_count: nulls,
        has_nan: false,
    }
}

/// f64 min/max stat over the non-NaN contributing values; NaN presence is
/// flagged and those values are excluded from min/max. `vals` carries the same
/// merged-view-resolved, one-entry-per-row shape [`i64_stat`] documents.
fn f64_stat(column_id: u32, vals: &[Option<u64>]) -> NumStat {
    let mut min: Option<f64> = None;
    let mut max: Option<f64> = None;
    let mut nulls = 0u32;
    let mut has_nan = false;
    for v in vals {
        match v {
            Some(bits) => {
                let f = f64::from_bits(*bits);
                if f.is_nan() {
                    has_nan = true;
                    continue;
                }
                min = Some(match min {
                    Some(m) if m.total_cmp(&f).is_le() => m,
                    _ => f,
                });
                max = Some(match max {
                    Some(m) if m.total_cmp(&f).is_ge() => m,
                    _ => f,
                });
            }
            None => nulls = nulls.saturating_add(1),
        }
    }
    NumStat {
        column_id,
        ty: FieldType::F64,
        min_bits: min.map(f64::to_bits).unwrap_or(0),
        max_bits: max.map(f64::to_bits).unwrap_or(0),
        null_count: nulls,
        has_nan,
    }
}

/// bool min/max stat (0/1 bits) over the contributing values. `vals` carries
/// the same merged-view-resolved, one-entry-per-row shape [`i64_stat`] documents.
fn bool_stat(column_id: u32, vals: &[Option<bool>]) -> NumStat {
    let mut min = 1u64;
    let mut max = 0u64;
    let mut nulls = 0u32;
    let mut any = false;
    for v in vals {
        match v {
            Some(b) => {
                any = true;
                let bit = u64::from(*b);
                min = min.min(bit);
                max = max.max(bit);
            }
            None => nulls = nulls.saturating_add(1),
        }
    }
    if !any {
        min = 0;
        max = 0;
    }
    NumStat {
        column_id,
        ty: FieldType::Bool,
        min_bits: min,
        max_bits: max,
        null_count: nulls,
        has_nan: false,
    }
}

/// Encodes `rows` into one block per the plans for its dynamic columns.
///
/// `rows` must be non-empty. Columns are emitted in a fixed order for
/// byte-deterministic output: the fixed columns in field order, then the
/// dynamic columns in `plans` order (ascending by id). Field order is *not*
/// ascending by id -- `flags` is column 8 and is staged before
/// `severity_text`, column 4 -- so the descriptors, and therefore
/// [`BlockWriteOut::payload`], are not in `column_id` order. Version 4's block
/// crc is defined over the pages in `column_id` order and is computed while the
/// row group is placed, not from the payload (ADR-0699 decision 2).
pub fn write_block(
    rows: &[ResolvedRow],
    plans: &[ColumnPlan],
    zstd_level: i32,
) -> Result<BlockWriteOut, LogSegError> {
    if rows.is_empty() {
        return Err(LogSegError::Corrupted("empty block".into()));
    }
    let n = rows.len();
    let mut pages: Vec<StagedPage> = Vec::new();
    let mut stats: Vec<NumStat> = Vec::new();

    // Fixed always-present integer columns.
    let all_present = vec![true; n];
    let ts: Vec<i64> = rows.iter().map(|r| r.ts_ns).collect();
    let (enc, b) = encode_i64(&ts);
    stage_column(&mut pages, COL_TS, &all_present, enc, b);
    let obs: Vec<i64> = rows.iter().map(|r| r.observed_ts_ns).collect();
    let (enc, b) = encode_i64(&obs);
    stage_column(&mut pages, COL_OBSERVED_TS, &all_present, enc, b);
    let sref: Vec<i64> = rows.iter().map(|r| i64::from(r.stream_ref)).collect();
    let (enc, b) = encode_i64(&sref);
    stage_column(&mut pages, COL_STREAM_REF, &all_present, enc, b);
    let sev: Vec<i64> = rows.iter().map(|r| i64::from(r.severity_num)).collect();
    let (enc, b) = encode_i64(&sev);
    stage_column(&mut pages, COL_SEVERITY_NUM, &all_present, enc, b);
    let flags: Vec<i64> = rows.iter().map(|r| i64::from(r.flags)).collect();
    let (enc, b) = encode_i64(&flags);
    stage_column(&mut pages, COL_FLAGS, &all_present, enc, b);

    // Fixed always-present string columns.
    let sev_text: Vec<&[u8]> = rows.iter().map(|r| r.severity_text.as_bytes()).collect();
    let (enc, b) = encode_strings(&sev_text);
    stage_column(&mut pages, COL_SEVERITY_TEXT, &all_present, enc, b);
    let body: Vec<&[u8]> = rows.iter().map(|r| r.body.as_bytes()).collect();
    let (enc, b) = encode_strings(&body);
    stage_column(&mut pages, COL_BODY, &all_present, enc, b);

    // Fixed optional fixed-width id columns.
    let trace_present: Vec<bool> = rows.iter().map(|r| r.trace_id.is_some()).collect();
    let trace_vals: Vec<&[u8]> = rows
        .iter()
        .filter_map(|r| r.trace_id.as_ref().map(|a| a.as_slice()))
        .collect();
    let (enc, b) = encode_fixed(&trace_vals, TRACE_ID_WIDTH);
    stage_column(&mut pages, COL_TRACE_ID, &trace_present, enc, b);
    let span_present: Vec<bool> = rows.iter().map(|r| r.span_id.is_some()).collect();
    let span_vals: Vec<&[u8]> = rows
        .iter()
        .filter_map(|r| r.span_id.as_ref().map(|a| a.as_slice()))
        .collect();
    let (enc, b) = encode_fixed(&span_vals, SPAN_ID_WIDTH);
    stage_column(&mut pages, COL_SPAN_ID, &span_present, enc, b);

    // Fixed optional attrs_raw column (canonical overflow bytes per row).
    let raw_present: Vec<bool> = rows.iter().map(|r| r.attrs_raw.is_some()).collect();
    let raw_vals: Vec<&[u8]> = rows.iter().filter_map(|r| r.attrs_raw.as_deref()).collect();
    let (enc, b) = encode_strings(&raw_vals);
    stage_column(&mut pages, COL_ATTRS_RAW, &raw_present, enc, b);

    // Dynamic columns, in plan order. The value pages carry each row's own
    // columnar occurrence ([`row_column`]); the stats carry each row's
    // merged-view winner ([`winner_value`]). Those are the same value for the
    // ordinary row that carries a name once, and deliberately differ for a row
    // with a duplicate of that name (ADR-0095): the page stores what the row
    // put in the column, the stat bounds what a reader will resolve.
    for plan in plans {
        let cid = plan.column_id;
        let present: Vec<bool> = rows.iter().map(|r| row_column(r, cid).is_some()).collect();
        match plan.ty {
            FieldType::I64 => {
                let vals: Vec<Option<i64>> = rows
                    .iter()
                    .map(|r| match row_column(r, cid) {
                        Some(ColumnValue::I64(v)) => Some(*v),
                        _ => None,
                    })
                    .collect();
                let stat_vals: Vec<Option<i64>> = rows
                    .iter()
                    .map(|r| match winner_value(r, cid) {
                        Some(ColumnValue::I64(v)) => Some(*v),
                        _ => None,
                    })
                    .collect();
                let present_vals: Vec<i64> = vals.iter().flatten().copied().collect();
                let (enc, b) = encode_i64(&present_vals);
                stats.push(i64_stat(cid, &stat_vals));
                stage_column(&mut pages, cid, &present, enc, b);
            }
            FieldType::F64 => {
                let vals: Vec<Option<u64>> = rows
                    .iter()
                    .map(|r| match row_column(r, cid) {
                        Some(ColumnValue::F64(v)) => Some(*v),
                        _ => None,
                    })
                    .collect();
                let stat_vals: Vec<Option<u64>> = rows
                    .iter()
                    .map(|r| match winner_value(r, cid) {
                        Some(ColumnValue::F64(v)) => Some(*v),
                        _ => None,
                    })
                    .collect();
                let present_vals: Vec<u64> = vals.iter().flatten().copied().collect();
                let (enc, b) = encode_f64(&present_vals);
                stats.push(f64_stat(cid, &stat_vals));
                stage_column(&mut pages, cid, &present, enc, b);
            }
            FieldType::Bool => {
                let vals: Vec<Option<bool>> = rows
                    .iter()
                    .map(|r| match row_column(r, cid) {
                        Some(ColumnValue::Bool(v)) => Some(*v),
                        _ => None,
                    })
                    .collect();
                let stat_vals: Vec<Option<bool>> = rows
                    .iter()
                    .map(|r| match winner_value(r, cid) {
                        Some(ColumnValue::Bool(v)) => Some(*v),
                        _ => None,
                    })
                    .collect();
                let present_vals: Vec<bool> = vals.iter().flatten().copied().collect();
                stats.push(bool_stat(cid, &stat_vals));
                stage_column(
                    &mut pages,
                    cid,
                    &present,
                    Enc::Bitmap,
                    encode_bitmap(&present_vals),
                );
            }
            FieldType::Str | FieldType::Bytes => {
                let vals: Vec<&[u8]> = rows
                    .iter()
                    .filter_map(|r| match row_column(r, cid) {
                        Some(ColumnValue::Str(v)) | Some(ColumnValue::Bytes(v)) => {
                            Some(v.as_slice())
                        }
                        _ => None,
                    })
                    .collect();
                let (enc, b) = encode_strings(&vals);
                stage_column(&mut pages, cid, &present, enc, b);
            }
        }
    }

    // Compress pages into a payload buffer, collecting descriptors.
    let mut payload = Vec::new();
    let mut descs: Vec<PageDesc> = Vec::with_capacity(pages.len());
    for p in &pages {
        descs.push(write_page(
            &mut payload,
            p.column_id,
            p.enc,
            &p.bytes,
            zstd_level,
        ));
    }

    let min_ts = ts.iter().copied().min().unwrap_or(0);
    let max_ts = ts.iter().copied().max().unwrap_or(0);
    let min_stream_ref = rows.iter().map(|r| r.stream_ref).min().unwrap_or(0);
    let max_stream_ref = rows.iter().map(|r| r.stream_ref).max().unwrap_or(0);

    Ok(BlockWriteOut {
        descs,
        payload,
        record_count: n as u32,
        stats,
        min_ts,
        max_ts,
        min_stream_ref,
        max_stream_ref,
    })
}

fn row_column(row: &ResolvedRow, column_id: u32) -> Option<&ColumnValue> {
    row.columns
        .iter()
        .find(|(cid, _)| *cid == column_id)
        .map(|(_, v)| v)
}

/// The value this row contributes to `column_id`'s [`NumStat`]: its resolved
/// merged-view value for that column's attribute name (its resource and scope
/// layer, overridden by its own attributes), keyed by the column that value's
/// own type resolves to ([`ResolvedRow::stat_winners`], ADR-0095 decision 2).
///
/// `None` means this row contributes to `null_count` only, which covers both
/// "the row resolves no value for this name" and "the row resolves one but of a
/// different type, so a reader materializing this typed column produces NULL
/// for this row".
fn winner_value(row: &ResolvedRow, column_id: u32) -> Option<&ColumnValue> {
    row.stat_winners
        .iter()
        .find(|(cid, _)| *cid == column_id)
        .map(|(_, v)| v)
}

/// A block's dictionary-shaped view of one Str/Bytes plan column: the column's
/// distinct value set (`dict`, in any order, possibly with entries no id
/// references) and one `Option<index into dict>` per block row (`Some` for a
/// present row, `None` for absent). The encoder derives the sorted RLOG
/// dictionary and the dict-versus-plain choice from the referenced distinct
/// values, so string encoding costs a sort per distinct value, not per row.
pub struct BlockStrDict<'a> {
    pub dict: &'a [Vec<u8>],
    pub ids: &'a [Option<u32>],
}

/// One block's data already in column-major form, the input to
/// [`write_block_columnar`]. Each per-row slice has `n` entries; the optional
/// fixed columns pair a per-row `*_present` bitmap with a dense `*_vals` slice
/// holding only the present rows. The dynamic columns are given as one
/// `Option<ColumnValue>` per row (the row's columnar occurrence) and one
/// `Option<ColumnValue>` per row for the stat winner, so the encoder never
/// gathers a value out of a per-row column vector.
pub struct ColumnarBlockInput<'a> {
    pub n: usize,
    pub ts: &'a [i64],
    pub observed_ts: &'a [i64],
    pub stream_ref: &'a [u32],
    pub severity_num: &'a [u8],
    pub flags: &'a [u32],
    pub severity_text: &'a [&'a [u8]],
    pub body: &'a [&'a [u8]],
    pub trace_present: &'a [bool],
    pub trace_vals: &'a [&'a [u8]],
    pub span_present: &'a [bool],
    pub span_vals: &'a [&'a [u8]],
    pub attrs_raw_present: &'a [bool],
    pub attrs_raw_vals: &'a [&'a [u8]],
    pub plans: &'a [ColumnPlan],
    /// Per plan (in `plans` order), one entry per row: the row's columnar
    /// occurrence for the column, `None` if absent.
    pub values: &'a [Vec<Option<ColumnValue>>],
    /// Per plan (in `plans` order), one entry per row: the row's merged-view
    /// stat winner for the column, `None` when the row contributes only to
    /// `null_count`.
    pub stat_values: &'a [Vec<Option<ColumnValue>>],
    /// Per plan (in `plans` order): `Some` when the plan is a Str/Bytes column
    /// supplied in dictionary shape, in which case its value page is encoded
    /// via [`encode_strings_dict`] (per distinct value, ADR-0109 decision 3)
    /// and `values[idx]` is ignored for that plan. `None` keeps the plain
    /// per-row `values` path unchanged.
    pub str_dicts: &'a [Option<BlockStrDict<'a>>],
}

/// Encodes one block from column-major input, byte-identical to
/// [`write_block`] fed the equivalent rows, but with no per-row value gather:
/// the value and stat arrays are supplied already grouped by column
/// (ADR-0109 decision 6, "Value gather ... Deleted").
///
/// This mirrors [`write_block`] line for line; the only substitution is that
/// each dynamic column's per-row value and stat come from `input.values` /
/// `input.stat_values` instead of the `row_column` / `winner_value` linear
/// scans.
pub fn write_block_columnar(
    input: &ColumnarBlockInput<'_>,
    zstd_level: i32,
) -> Result<BlockWriteOut, LogSegError> {
    let n = input.n;
    if n == 0 {
        return Err(LogSegError::Corrupted("empty block".into()));
    }
    let mut pages: Vec<StagedPage> = Vec::new();
    let mut stats: Vec<NumStat> = Vec::new();

    // Fixed always-present integer columns.
    let all_present = vec![true; n];
    let (enc, b) = encode_i64(input.ts);
    stage_column(&mut pages, COL_TS, &all_present, enc, b);
    let (enc, b) = encode_i64(input.observed_ts);
    stage_column(&mut pages, COL_OBSERVED_TS, &all_present, enc, b);
    let sref: Vec<i64> = input.stream_ref.iter().map(|r| i64::from(*r)).collect();
    let (enc, b) = encode_i64(&sref);
    stage_column(&mut pages, COL_STREAM_REF, &all_present, enc, b);
    let sev: Vec<i64> = input.severity_num.iter().map(|r| i64::from(*r)).collect();
    let (enc, b) = encode_i64(&sev);
    stage_column(&mut pages, COL_SEVERITY_NUM, &all_present, enc, b);
    let flags: Vec<i64> = input.flags.iter().map(|r| i64::from(*r)).collect();
    let (enc, b) = encode_i64(&flags);
    stage_column(&mut pages, COL_FLAGS, &all_present, enc, b);

    // Fixed always-present string columns.
    let (enc, b) = encode_strings(input.severity_text);
    stage_column(&mut pages, COL_SEVERITY_TEXT, &all_present, enc, b);
    let (enc, b) = encode_strings(input.body);
    stage_column(&mut pages, COL_BODY, &all_present, enc, b);

    // Fixed optional fixed-width id columns.
    let (enc, b) = encode_fixed(input.trace_vals, TRACE_ID_WIDTH);
    stage_column(&mut pages, COL_TRACE_ID, input.trace_present, enc, b);
    let (enc, b) = encode_fixed(input.span_vals, SPAN_ID_WIDTH);
    stage_column(&mut pages, COL_SPAN_ID, input.span_present, enc, b);

    // Fixed optional attrs_raw column (canonical overflow bytes per row).
    let (enc, b) = encode_strings(input.attrs_raw_vals);
    stage_column(&mut pages, COL_ATTRS_RAW, input.attrs_raw_present, enc, b);

    // Dynamic columns, in plan order.
    for (idx, plan) in input.plans.iter().enumerate() {
        let cid = plan.column_id;
        let vals = &input.values[idx];
        let stat_vals = &input.stat_values[idx];
        let present: Vec<bool> = vals.iter().map(Option::is_some).collect();
        match plan.ty {
            FieldType::I64 => {
                let sv: Vec<Option<i64>> = stat_vals
                    .iter()
                    .map(|v| match v {
                        Some(ColumnValue::I64(x)) => Some(*x),
                        _ => None,
                    })
                    .collect();
                let present_vals: Vec<i64> = vals
                    .iter()
                    .filter_map(|v| match v {
                        Some(ColumnValue::I64(x)) => Some(*x),
                        _ => None,
                    })
                    .collect();
                let (enc, b) = encode_i64(&present_vals);
                stats.push(i64_stat(cid, &sv));
                stage_column(&mut pages, cid, &present, enc, b);
            }
            FieldType::F64 => {
                let sv: Vec<Option<u64>> = stat_vals
                    .iter()
                    .map(|v| match v {
                        Some(ColumnValue::F64(x)) => Some(*x),
                        _ => None,
                    })
                    .collect();
                let present_vals: Vec<u64> = vals
                    .iter()
                    .filter_map(|v| match v {
                        Some(ColumnValue::F64(x)) => Some(*x),
                        _ => None,
                    })
                    .collect();
                let (enc, b) = encode_f64(&present_vals);
                stats.push(f64_stat(cid, &sv));
                stage_column(&mut pages, cid, &present, enc, b);
            }
            FieldType::Bool => {
                let sv: Vec<Option<bool>> = stat_vals
                    .iter()
                    .map(|v| match v {
                        Some(ColumnValue::Bool(x)) => Some(*x),
                        _ => None,
                    })
                    .collect();
                let present_vals: Vec<bool> = vals
                    .iter()
                    .filter_map(|v| match v {
                        Some(ColumnValue::Bool(x)) => Some(*x),
                        _ => None,
                    })
                    .collect();
                stats.push(bool_stat(cid, &sv));
                stage_column(
                    &mut pages,
                    cid,
                    &present,
                    Enc::Bitmap,
                    encode_bitmap(&present_vals),
                );
            }
            FieldType::Str | FieldType::Bytes => {
                if let Some(dp) = &input.str_dicts[idx] {
                    // Dictionary-shaped column: encode per distinct value.
                    let dpresent: Vec<bool> = dp.ids.iter().map(Option::is_some).collect();
                    let present_ids: Vec<u32> = dp.ids.iter().filter_map(|x| *x).collect();
                    let dref: Vec<&[u8]> = dp.dict.iter().map(Vec::as_slice).collect();
                    let (enc, b) = encode_strings_dict(&dref, &present_ids);
                    stage_column(&mut pages, cid, &dpresent, enc, b);
                } else {
                    let vv: Vec<&[u8]> = vals
                        .iter()
                        .filter_map(|v| match v {
                            Some(ColumnValue::Str(x)) | Some(ColumnValue::Bytes(x)) => {
                                Some(x.as_slice())
                            }
                            _ => None,
                        })
                        .collect();
                    let (enc, b) = encode_strings(&vv);
                    stage_column(&mut pages, cid, &present, enc, b);
                }
            }
        }
    }

    // Compress pages into a payload buffer, collecting descriptors.
    let mut payload = Vec::new();
    let mut descs: Vec<PageDesc> = Vec::with_capacity(pages.len());
    for p in &pages {
        descs.push(write_page(
            &mut payload,
            p.column_id,
            p.enc,
            &p.bytes,
            zstd_level,
        ));
    }

    let min_ts = input.ts.iter().copied().min().unwrap_or(0);
    let max_ts = input.ts.iter().copied().max().unwrap_or(0);
    let min_stream_ref = input.stream_ref.iter().copied().min().unwrap_or(0);
    let max_stream_ref = input.stream_ref.iter().copied().max().unwrap_or(0);

    Ok(BlockWriteOut {
        descs,
        payload,
        record_count: n as u32,
        stats,
        min_ts,
        max_ts,
        min_stream_ref,
        max_stream_ref,
    })
}

/// A decoded string column, kept in whichever shape its page carried
/// (ADR-0099 decision 4). A dictionary page keeps its distinct set and per-row
/// ids instead of materializing one owned `Vec<u8>` per row; a plain page keeps
/// the per-row values. Both are addressed by block row position and carry
/// presence separately: an absent row reads `None` either way.
pub(crate) enum StrColumn {
    /// Per-row values, `None` for an absent row. What a plain page decodes to.
    Plain(Vec<Option<Vec<u8>>>),
    /// The distinct values plus one id per block row: `Some(id)` indexes `dict`,
    /// `None` marks an absent row (the presence bitmap, kept out of the id
    /// vector rather than folded in as a sentinel). Every `Some(id)` is
    /// `< dict.len()`, validated at decode.
    Dict {
        dict: Vec<Vec<u8>>,
        ids: Vec<Option<u32>>,
    },
}

/// The borrowed dictionary form of a string column: the distinct values and
/// one id per block row (`None` for an absent row). Returned by
/// [`DecodedBlock::str_dict`] for the columnar view to build an Arrow
/// dictionary array from.
type StrDictRef<'a> = (&'a [Vec<u8>], &'a [Option<u32>]);

impl StrColumn {
    /// The bytes at block row `row`, or `None` when the row is absent (or out of
    /// range). Both shapes read identically here, which is what lets the storage
    /// shape stay invisible above [`DecodedBlock`].
    fn cell(&self, row: usize) -> Option<&[u8]> {
        match self {
            StrColumn::Plain(v) => v.get(row)?.as_deref(),
            StrColumn::Dict { dict, ids } => {
                let id = (*ids.get(row)?)? as usize;
                dict.get(id).map(Vec::as_slice)
            }
        }
    }
}

/// A block's decoded columns of one storage kind, addressed by column id.
///
/// Column ids are dense and small (fixed 0..=9, dynamic from
/// [`FIRST_DYNAMIC_COL`] up to the block's dynamic-column budget), so a `Vec`
/// slot per id resolves a column with one bounds-checked index and no hashing.
/// SipHash over a `&u32` key was 6% of warm-pass self time on the scan's hot
/// loop; there is no HashDoS surface on an internal, per-block map (#875).
struct ColMap<T> {
    /// One slot per column id; `None` where the block carries no such column
    /// (absent from every row, or projected away by the scan's column filter).
    cols: Vec<Option<T>>,
}

impl<T> ColMap<T> {
    fn new() -> Self {
        ColMap { cols: Vec::new() }
    }

    fn get(&self, column_id: u32) -> Option<&T> {
        self.cols.get(column_id as usize).and_then(Option::as_ref)
    }

    fn insert(&mut self, column_id: u32, value: T) {
        let idx = column_id as usize;
        if idx >= self.cols.len() {
            self.cols.resize_with(idx + 1, || None);
        }
        self.cols[idx] = Some(value);
    }

    fn values(&self) -> impl Iterator<Item = &T> {
        self.cols.iter().flatten()
    }

    /// Bytes held by the slot vector itself, excluding whatever the slots point
    /// at. The vector is sized by the largest column id in the block rather
    /// than by how many columns it carries, so a sparse block charges more here
    /// than its column count suggests; leaving it out under-reports resident
    /// memory and lets a pool limit over-admit decoded blocks.
    fn slot_bytes(&self) -> usize {
        self.cols.capacity() * std::mem::size_of::<Option<T>>()
    }
}

/// A byte-valued column resolved once by id: a string column (plain or
/// dictionary) or a fixed-width id column. A given column id is only ever one of
/// the two, so [`DecodedBlock::bytes_col`] resolves it with a single lookup and
/// [`ColumnarBlockView::bytes_cursor`](crate::ColumnarBlockView) walks it per row
/// with none. It yields cell bytes, never the storage vector, so ADR-0099
/// decision 4's string-storage change stays invisible to callers.
pub(crate) enum BytesColRef<'a> {
    Str(&'a StrColumn),
    Fixed(&'a [Option<Vec<u8>>]),
}

impl<'a> BytesColRef<'a> {
    /// The bytes at block row `row`, or `None` for an absent row. Borrowed from
    /// the block for `'a`, not from the [`BytesColRef`], so a cursor can hand out
    /// a cell that outlives the transient cursor.
    pub(crate) fn cell(&self, row: usize) -> Option<&'a [u8]> {
        match self {
            BytesColRef::Str(s) => s.cell(row),
            BytesColRef::Fixed(v) => v.get(row)?.as_deref(),
        }
    }
}

/// A decoded block: per-column, per-row values. Every column vector has length
/// `record_count`; `None` marks a row where the column has no value.
///
/// A block decoded through [`read_block_columns`] with a column filter holds
/// only the filtered columns. A column the filter excluded is indistinguishable
/// from a column the block never carried: its accessor returns `None`. Callers
/// that project must therefore know which columns they asked for; nothing here
/// can tell them apart, by design (an absent page and a skipped page decode to
/// the same nothing).
pub struct DecodedBlock {
    record_count: usize,
    i64_cols: ColMap<Vec<Option<i64>>>,
    f64_cols: ColMap<Vec<Option<u64>>>,
    bool_cols: ColMap<Vec<Option<bool>>>,
    str_cols: ColMap<StrColumn>,
    fixed_cols: ColMap<Vec<Option<Vec<u8>>>>,
    /// Count of column resolutions by id (`i64_col`, `bytes_col`, ... ), for
    /// tests that pin the scan does O(columns) resolutions per block, not
    /// O(rows x columns) (#875). A per-cell accessor bumps it once per cell; a
    /// cursor bumps it once per column and then indexes the resolved slice with
    /// no further bump. `Cell`, not atomic: a block is read by one thread and
    /// this must not add a barrier to the hot per-cell path.
    col_lookups: Cell<u64>,
    /// Whether any page descriptor in this block named [`COL_ATTRS_RAW`], read
    /// off the header and independent of the column filter (see
    /// [`DecodedBlock::has_attrs_raw_page`]).
    attrs_raw_page: bool,
    pages_decoded: usize,
    pages_skipped: usize,
    page_bytes_fetched: u64,
    page_bytes_decoded: u64,
}

impl DecodedBlock {
    pub fn record_count(&self) -> usize {
        self.record_count
    }

    /// Pages this decode decompressed and decoded (value pages and presence
    /// bitmaps alike).
    pub fn pages_decoded(&self) -> usize {
        self.pages_decoded
    }

    /// Pages this decode skipped because the column filter excluded them. Zero
    /// for an all-columns decode. This is the observable proof that column
    /// projection reached the page level rather than being applied after decode.
    pub fn pages_skipped(&self) -> usize {
        self.pages_skipped
    }

    /// Stored bytes of every page present in this block, regardless of whether
    /// the column filter kept it: the "fetched" side of ADR-0107 decision 4's
    /// decode-time column-filtering measurement. Summed from each
    /// [`PageDesc::len`], so it counts stored (post-compression) bytes, the same
    /// units the block's payload occupies -- decode-time accounting, not wire
    /// bytes.
    pub fn page_bytes_fetched(&self) -> u64 {
        self.page_bytes_fetched
    }

    /// Stored bytes of the pages this decode actually decompressed and decoded,
    /// i.e. only the columns the filter kept: the "decoded" side of the same
    /// measurement. Equal to [`Self::page_bytes_fetched`] for an all-columns
    /// decode; strictly less whenever a projection skipped any present page.
    pub fn page_bytes_decoded(&self) -> u64 {
        self.page_bytes_decoded
    }

    /// Whether this block carries any page for the `attrs_raw` overflow column.
    ///
    /// Read off the page descriptors in the block header, so it is true for a
    /// block that has such a page even when the column filter excluded it and
    /// nothing of it was decompressed. A block whose records all fit their
    /// FIELD_DIR columns has no `attrs_raw` page at all
    /// (`absent_column_occupies_no_page`), which is what makes this a metadata
    /// read rather than a decode.
    pub fn has_attrs_raw_page(&self) -> bool {
        self.attrs_raw_page
    }

    /// The heap bytes this decoded block holds resident: every column vector's
    /// allocation plus every present string and fixed-width cell's own buffer.
    ///
    /// A caller that keeps a block alive while it drains the block (the SQL
    /// logs scan's columnar path, which holds a borrowed view) has to charge
    /// its memory pool for this. The per-cell term is the reason the figure is
    /// computed here rather than estimated from `record_count`: a byte-valued
    /// column of `n` rows is `n` separate allocations plus the vector spine, so
    /// counting spines alone understates a body or string-attribute column
    /// several-fold.
    ///
    /// Capacity, not length, because capacity is what is allocated. The
    /// per-kind `HashMap` spines are not counted: they hold one entry per
    /// decoded column, bounded by the scan's column selection and negligible
    /// against the cells.
    pub fn decoded_heap_bytes(&self) -> usize {
        let mut total = 0usize;
        // The slot vectors themselves, before the columns they hold.
        total += self.i64_cols.slot_bytes();
        total += self.f64_cols.slot_bytes();
        total += self.bool_cols.slot_bytes();
        total += self.str_cols.slot_bytes();
        total += self.fixed_cols.slot_bytes();
        for v in self.i64_cols.values() {
            total += v.capacity() * std::mem::size_of::<Option<i64>>();
        }
        for v in self.f64_cols.values() {
            total += v.capacity() * std::mem::size_of::<Option<u64>>();
        }
        for v in self.bool_cols.values() {
            total += v.capacity() * std::mem::size_of::<Option<bool>>();
        }
        // A dictionary-form string column holds its distinct values once plus a
        // narrow id per row, not one owned buffer per row: charging it as though
        // every row still owned a `Vec<u8>` would over-report by the
        // deduplication factor and make `ravel-sql` charge its pool for memory
        // that no longer exists (ADR-0099 decision 4).
        for col in self.str_cols.values() {
            match col {
                StrColumn::Plain(v) => {
                    total += v.capacity() * std::mem::size_of::<Option<Vec<u8>>>();
                    for cell in v.iter().flatten() {
                        total += cell.capacity();
                    }
                }
                StrColumn::Dict { dict, ids } => {
                    total += ids.capacity() * std::mem::size_of::<Option<u32>>();
                    total += dict.capacity() * std::mem::size_of::<Vec<u8>>();
                    for entry in dict {
                        total += entry.capacity();
                    }
                }
            }
        }
        for v in self.fixed_cols.values() {
            total += v.capacity() * std::mem::size_of::<Option<Vec<u8>>>();
            for cell in v.iter().flatten() {
                total += cell.capacity();
            }
        }
        total
    }
    /// Column resolutions by id since decode: see [`Self::col_lookups`].
    pub fn column_lookups(&self) -> u64 {
        self.col_lookups.get()
    }

    #[inline]
    fn bump_lookup(&self) {
        self.col_lookups.set(self.col_lookups.get() + 1);
    }

    pub fn i64_col(&self, column_id: u32) -> Option<&[Option<i64>]> {
        self.bump_lookup();
        self.i64_cols.get(column_id).map(Vec::as_slice)
    }
    pub fn f64_col(&self, column_id: u32) -> Option<&[Option<u64>]> {
        self.bump_lookup();
        self.f64_cols.get(column_id).map(Vec::as_slice)
    }
    pub fn bool_col(&self, column_id: u32) -> Option<&[Option<bool>]> {
        self.bump_lookup();
        self.bool_cols.get(column_id).map(Vec::as_slice)
    }

    /// The bytes of string column `column_id` at block row `row`, or `None` when
    /// the column is absent (or projected away) or the row has no value. Both
    /// the plain and dictionary storage shapes read through here, so a caller
    /// never learns which one the column is (ADR-0099 decision 4).
    pub(crate) fn str_at(&self, column_id: u32, row: usize) -> Option<&[u8]> {
        self.bump_lookup();
        self.str_cols.get(column_id)?.cell(row)
    }

    /// Resolve a byte-valued column (string or fixed-width) by id once, for a
    /// cursor that then walks it per row with no further lookup. `None` when the
    /// block carries no such column (absent or projected away). One lookup even
    /// though a byte column can live in either the string or the fixed map: a
    /// given id is only ever one of the two.
    pub(crate) fn bytes_col(&self, column_id: u32) -> Option<BytesColRef<'_>> {
        self.bump_lookup();
        if let Some(s) = self.str_cols.get(column_id) {
            return Some(BytesColRef::Str(s));
        }
        self.fixed_cols
            .get(column_id)
            .map(|v| BytesColRef::Fixed(v.as_slice()))
    }

    /// The dictionary form of string column `column_id`: its distinct values and
    /// one id per block row (`None` for an absent row). `None` when the column is
    /// absent, projected away, or stored in plain form -- a plain page is read
    /// through [`Self::str_at`], never forced into a dictionary here.
    pub(crate) fn str_dict(&self, column_id: u32) -> Option<StrDictRef<'_>> {
        self.bump_lookup();
        match self.str_cols.get(column_id)? {
            StrColumn::Dict { dict, ids } => Some((dict, ids)),
            StrColumn::Plain(_) => None,
        }
    }

    pub fn fixed_col(&self, column_id: u32) -> Option<&[Option<Vec<u8>>]> {
        self.bump_lookup();
        self.fixed_cols.get(column_id).map(Vec::as_slice)
    }

    /// Test-only fused view of a string column, `None` when the column is absent.
    /// Rebuilds the pre-ADR-0099 `Vec<Option<Vec<u8>>>` shape so existing
    /// assertions read unchanged regardless of the storage shape.
    #[cfg(test)]
    fn str_col_fused(&self, column_id: u32) -> Option<Vec<Option<Vec<u8>>>> {
        let _ = self.str_cols.get(column_id)?;
        Some(
            (0..self.record_count)
                .map(|row| self.str_at(column_id, row).map(<[u8]>::to_vec))
                .collect(),
        )
    }
}

/// How a column decodes, resolved from its id (fixed) or its plan (dynamic).
enum ColKind {
    I64,
    F64,
    Bool,
    Str,
    Fixed(usize),
}

fn column_kind(column_id: u32, plans: &[ColumnPlan]) -> Result<ColKind, LogSegError> {
    Ok(match column_id {
        COL_TS | COL_OBSERVED_TS | COL_STREAM_REF | COL_SEVERITY_NUM | COL_FLAGS => ColKind::I64,
        COL_SEVERITY_TEXT | COL_BODY | COL_ATTRS_RAW => ColKind::Str,
        COL_TRACE_ID => ColKind::Fixed(TRACE_ID_WIDTH),
        COL_SPAN_ID => ColKind::Fixed(SPAN_ID_WIDTH),
        _ => {
            let plan = plans
                .iter()
                .find(|p| p.column_id == column_id)
                .ok_or_else(|| LogSegError::Corrupted(format!("unknown column id {column_id}")))?;
            match plan.ty {
                FieldType::I64 => ColKind::I64,
                FieldType::F64 => ColKind::F64,
                FieldType::Bool => ColKind::Bool,
                FieldType::Str | FieldType::Bytes => ColKind::Str,
            }
        }
    })
}

/// The decoded bytes of a page that the column filter kept. Only ever called
/// for a page whose column was grouped, i.e. one the filter kept, so a `None`
/// here would be an internal inconsistency rather than bad input; it is still
/// reported as a typed error rather than unwrapped.
fn page(pages: &[Option<Vec<u8>>], idx: usize) -> Result<&[u8], LogSegError> {
    pages
        .get(idx)
        .and_then(|p| p.as_deref())
        .ok_or_else(|| LogSegError::Corrupted("page not decoded".into()))
}

/// Scatters `present`-length-`record_count` values into a per-row vector.
/// `values` holds only the present entries, in row order.
fn scatter<T: Clone>(present: &[bool], values: Vec<T>) -> Result<Vec<Option<T>>, LogSegError> {
    let mut out = Vec::with_capacity(present.len());
    let mut it = values.into_iter();
    for &p in present {
        if p {
            let v = it
                .next()
                .ok_or_else(|| LogSegError::Corrupted("presence/value count mismatch".into()))?;
            out.push(Some(v));
        } else {
            out.push(None);
        }
    }
    if it.next().is_some() {
        return Err(LogSegError::Corrupted(
            "value page longer than presence".into(),
        ));
    }
    Ok(out)
}

/// Decodes every column of a block, verifying its crc32c first.
///
/// This is the all-columns case, and it is what
/// [`crate::ranged::RlogRangeReader`] (the compaction merge's reader) and
/// [`crate::RlogReader::scan_pruned`] use: identical decoded output to before
/// column projection existed. Use [`read_block_columns`] to decode a subset.
pub fn read_block(
    bytes: &[u8],
    expected_crc: u32,
    plans: &[ColumnPlan],
    max_uncomp: u64,
) -> Result<DecodedBlock, LogSegError> {
    read_block_columns(bytes, expected_crc, plans, max_uncomp, None)
}

/// Decodes a block, verifying its crc32c first, decompressing and decoding only
/// the pages of the columns `columns` names (ADR-0087 decision 3).
///
/// `columns == None` is the all-columns case ([`read_block`]). Otherwise every
/// page whose `column_id` is not in the set is walked past without a
/// `read_page` call, so its stored bytes are never decompressed and its values
/// are never materialized; the resulting [`DecodedBlock`] reports that column as
/// absent. Both a column's presence bitmap page and its value page are governed
/// by the same decision, so a projected column is never left half-decoded.
///
/// The block's crc32c covers the whole block and is verified in full regardless
/// of the filter: projection changes what is decoded, never what is checked.
/// Every page descriptor is still parsed and every page's stored extent is still
/// walked, so a truncated or over-long block is rejected exactly as it is
/// without a filter.
pub fn read_block_columns(
    bytes: &[u8],
    expected_crc: u32,
    plans: &[ColumnPlan],
    max_uncomp: u64,
    columns: Option<&ColumnIdSet>,
) -> Result<DecodedBlock, LogSegError> {
    if crc32c::crc32c(bytes) != expected_crc {
        return Err(LogSegError::Corrupted("block crc mismatch".into()));
    }
    let mut pos = 0usize;
    let record_count = get_uvarint(bytes, &mut pos)?;
    if record_count > MAX_RECORDS {
        return Err(LogSegError::Corrupted(format!(
            "record_count {record_count} over cap"
        )));
    }
    let record_count = record_count as usize;
    let page_count = get_uvarint(bytes, &mut pos)?;
    if page_count > MAX_PAGES {
        return Err(LogSegError::Corrupted(format!(
            "page_count {page_count} over cap"
        )));
    }
    let page_count = page_count as usize;

    let mut descs: Vec<PageDesc> = Vec::with_capacity(page_count.min(MAX_PAGES as usize));
    for _ in 0..page_count {
        let column_id = get_uvarint(bytes, &mut pos)?;
        if column_id > MAX_COLUMN_ID {
            return Err(LogSegError::Corrupted(format!(
                "column_id {column_id} over cap {MAX_COLUMN_ID}"
            )));
        }
        let column_id = u32::try_from(column_id)
            .map_err(|_| LogSegError::Corrupted("column id out of range".into()))?;
        let enc = Enc::from_u8(
            *bytes
                .get(pos)
                .ok_or_else(|| LogSegError::Corrupted("block truncated at enc".into()))?,
        )?;
        pos += 1;
        let comp = *bytes
            .get(pos)
            .ok_or_else(|| LogSegError::Corrupted("block truncated at comp".into()))?;
        pos += 1;
        let len = get_uvarint(bytes, &mut pos)?;
        let uncomp_len = get_uvarint(bytes, &mut pos)?;
        descs.push(PageDesc {
            column_id,
            enc,
            comp,
            len,
            uncomp_len,
        });
    }

    // Whether a column's pages are decoded at all. `None` selects everything.
    let wanted = |cid: u32| match columns {
        None => true,
        Some(set) => set.contains(&cid),
    };

    // Slice each page's stored bytes and decompress to encoded bytes. A page
    // belonging to an unwanted column is walked past: its extent is still
    // validated (so truncation is still caught) but `read_page` is not called,
    // so its bytes are never decompressed.
    let mut page_bytes: Vec<Option<Vec<u8>>> = Vec::with_capacity(descs.len());
    let mut pages_decoded = 0usize;
    let mut pages_skipped = 0usize;
    // "Fetched" sums every present page's stored length; "decoded" sums only the
    // pages the filter kept. Their gap is the column-filtering waste (ADR-0107
    // decision 4). Stored (post-compression) bytes, matching `PageDesc::len`.
    let mut page_bytes_fetched = 0u64;
    let mut page_bytes_decoded = 0u64;
    for d in &descs {
        let len = usize::try_from(d.len)
            .map_err(|_| LogSegError::Corrupted("page len out of range".into()))?;
        let end = pos
            .checked_add(len)
            .ok_or_else(|| LogSegError::Corrupted("page range overflow".into()))?;
        let stored = bytes
            .get(pos..end)
            .ok_or_else(|| LogSegError::Corrupted("page range out of bounds".into()))?;
        page_bytes_fetched = page_bytes_fetched.saturating_add(d.len);
        if wanted(d.column_id) {
            page_bytes.push(Some(read_page(stored, d, max_uncomp)?));
            pages_decoded += 1;
            page_bytes_decoded = page_bytes_decoded.saturating_add(d.len);
        } else {
            page_bytes.push(None);
            pages_skipped += 1;
        }
        pos = end;
    }
    if pos != bytes.len() {
        return Err(LogSegError::Corrupted(
            "trailing bytes after block pages".into(),
        ));
    }

    decode_columns(
        record_count,
        &descs,
        &page_bytes,
        plans,
        PageCounters {
            decoded: pages_decoded,
            skipped: pages_skipped,
            bytes_fetched: page_bytes_fetched,
            bytes_decoded: page_bytes_decoded,
        },
    )
}

/// Decodes one version-4 block from pages the caller located through PAGE_DIR
/// (ADR-0699 decision 2). A version-4 block has no header and no contiguous
/// byte range: its pages live in its row group's column chunks, so locating and
/// checksum-verifying them is the caller's job and this only decodes them.
///
/// `descs` is the block's page descriptors in `column_id` order -- the order
/// PAGE_DIR lists them in and the order the SKIP_IDX level-0 block crc covers
/// them in -- and `page_bytes` is the parallel decompressed-to-encoded bytes,
/// `None` for a column the projection dropped and whose stored bytes were
/// therefore never read at all. That is the difference from version 3's
/// projection: there a skipped page's bytes were present and merely not
/// decompressed, here they never left the object store.
pub fn read_block_pages(
    record_count: usize,
    descs: &[PageDesc],
    page_bytes: &[Option<Vec<u8>>],
    plans: &[ColumnPlan],
    counters: PageCounters,
) -> Result<DecodedBlock, LogSegError> {
    if record_count > MAX_RECORDS as usize {
        return Err(LogSegError::Corrupted(format!(
            "record_count {record_count} over cap"
        )));
    }
    if descs.len() as u64 > MAX_PAGES {
        return Err(LogSegError::Corrupted(format!(
            "page_count {} over cap",
            descs.len()
        )));
    }
    decode_columns(record_count, descs, page_bytes, plans, counters)
}

/// How much of a block's page bytes a read actually touched
/// (docs/adrs/0107-log-segment-block-range-fetch.md decision 4). `fetched` sums
/// every page the block has, `decoded` only the pages the projection kept;
/// their gap is the column-filtering waste.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct PageCounters {
    pub decoded: usize,
    pub skipped: usize,
    pub bytes_fetched: u64,
    pub bytes_decoded: u64,
}

/// Turns a block's page descriptors and their decompressed bytes into a
/// [`DecodedBlock`]. Shared by the version-3 block reader and the version-4
/// page reader: only how the pages are located differs between them, never how
/// a column is rebuilt from a presence page and a value page.
///
/// A page whose entry in `page_bytes` is `None` was not read; its column is
/// left out of the result exactly as an absent column would be.
fn decode_columns(
    record_count: usize,
    descs: &[PageDesc],
    page_bytes: &[Option<Vec<u8>>],
    plans: &[ColumnPlan],
    counters: PageCounters,
) -> Result<DecodedBlock, LogSegError> {
    if descs.len() != page_bytes.len() {
        return Err(LogSegError::Corrupted(
            "page descriptor and page byte counts differ".into(),
        ));
    }
    let wanted = |i: usize| page_bytes[i].is_some();

    // Group descriptor indices by column id, preserving order. Unwanted columns
    // are not grouped at all, so nothing below ever looks at their pages.
    let mut order: Vec<u32> = Vec::new();
    let mut groups: HashMap<u32, Vec<usize>> = HashMap::new();
    for (i, d) in descs.iter().enumerate() {
        if !wanted(i) {
            continue;
        }
        groups.entry(d.column_id).or_insert_with(|| {
            order.push(d.column_id);
            Vec::new()
        });
        if let Some(g) = groups.get_mut(&d.column_id) {
            g.push(i);
        }
    }

    let mut out = DecodedBlock {
        record_count,
        i64_cols: ColMap::new(),
        f64_cols: ColMap::new(),
        bool_cols: ColMap::new(),
        str_cols: ColMap::new(),
        fixed_cols: ColMap::new(),
        col_lookups: Cell::new(0),
        attrs_raw_page: descs.iter().any(|d| d.column_id == COL_ATTRS_RAW),
        pages_decoded: counters.decoded,
        pages_skipped: counters.skipped,
        page_bytes_fetched: counters.bytes_fetched,
        page_bytes_decoded: counters.bytes_decoded,
    };

    for column_id in order {
        let idxs = &groups[&column_id];
        let (present, value_idx): (Vec<bool>, usize) = match idxs.as_slice() {
            [v] => (vec![true; record_count], *v),
            [p, v] => {
                if descs[*p].enc != Enc::Bitmap {
                    return Err(LogSegError::Corrupted("presence page not a bitmap".into()));
                }
                (decode_bitmap(page(page_bytes, *p)?, record_count)?, *v)
            }
            _ => {
                return Err(LogSegError::Corrupted(format!(
                    "column {column_id} has {} pages",
                    idxs.len()
                )));
            }
        };
        let present_count = present.iter().filter(|&&b| b).count();
        let enc = descs[value_idx].enc;
        let encoded = page(page_bytes, value_idx)?;
        match column_kind(column_id, plans)? {
            ColKind::I64 => {
                let vals = decode_i64(enc, encoded, present_count)?;
                out.i64_cols.insert(column_id, scatter(&present, vals)?);
            }
            ColKind::F64 => {
                let vals = decode_f64(enc, encoded, present_count)?;
                out.f64_cols.insert(column_id, scatter(&present, vals)?);
            }
            ColKind::Bool => {
                if enc != Enc::Bitmap {
                    return Err(LogSegError::Corrupted(
                        "bool value page not a bitmap".into(),
                    ));
                }
                let vals = decode_bitmap(encoded, present_count)?;
                out.bool_cols.insert(column_id, scatter(&present, vals)?);
            }
            ColKind::Str => {
                // Presence is applied by scattering against the block's presence
                // bitmap; the page's ids are per present row, so an absent row
                // gets a `None` slot rather than a sentinel id (ADR-0099
                // decision 4). A dict page keeps its distinct set intact.
                let col = match decode_strings_columnar(enc, encoded, present_count)? {
                    DecodedStrings::Plain(vals) => StrColumn::Plain(scatter(&present, vals)?),
                    DecodedStrings::Dict { dict, ids } => StrColumn::Dict {
                        dict,
                        ids: scatter(&present, ids)?,
                    },
                };
                out.str_cols.insert(column_id, col);
            }
            ColKind::Fixed(width) => {
                let vals = decode_fixed(enc, encoded, present_count, width)?;
                out.fixed_cols.insert(column_id, scatter(&present, vals)?);
            }
        }
    }

    Ok(out)
}

#[cfg(test)]
#[allow(clippy::expect_used)]
mod tests {
    use super::*;

    /// A page descriptor's `column_id` is read from the object, and `ColMap`
    /// indexes a dense slot vector by it, so the allocation follows the largest
    /// id rather than the column count. Without a cap a single block claiming a
    /// `column_id` near `u32::MAX` resizes that vector to billions of slots and
    /// exhausts memory before any pool limit can see it.
    ///
    /// This must fail as a typed `Corrupted` error. Deleting the `MAX_COLUMN_ID`
    /// check makes this test attempt a multi-gigabyte allocation instead of
    /// returning, which is how it was demonstrated failing.
    #[test]
    fn a_column_id_over_the_cap_is_rejected_before_it_allocates() {
        // record_count, page_count, then one descriptor whose column_id is far
        // past the cap: enc, comp, len, uncomp_len follow it.
        let mut block = Vec::new();
        put_uvarint(&mut block, 1); // record_count
        put_uvarint(&mut block, 1); // page_count
        put_uvarint(&mut block, u64::from(u32::MAX)); // column_id, wildly over cap
        block.push(0); // enc
        block.push(0); // comp
        put_uvarint(&mut block, 0); // len
        put_uvarint(&mut block, 0); // uncomp_len
        let crc = crc32c::crc32c(&block);

        match read_block_columns(&block, crc, &[], 1 << 20, None) {
            Err(LogSegError::Corrupted(msg)) => assert!(
                msg.contains("column_id") && msg.contains("over cap"),
                "expected a column_id cap error naming the value, got: {msg}"
            ),
            Err(other) => panic!("expected Corrupted, got {other:?}"),
            Ok(_) => panic!("a column_id over the cap must be rejected, not decoded"),
        }
    }

    /// The slot vector is sized by the largest column id, not by how many
    /// columns the block carries, so a block with one high-id column charges far
    /// more than one column's worth. Leaving it out of `decoded_heap_bytes`
    /// under-reports resident memory and lets a memory pool over-admit.
    ///
    /// This asserts through `decoded_heap_bytes`, the function that is actually
    /// relied on, NOT through `ColMap::slot_bytes` directly. A first version of
    /// this test called `slot_bytes` and passed with the charge removed from
    /// `decoded_heap_bytes` entirely -- it pinned the helper while the caller
    /// stayed broken.
    ///
    /// Pins a magnitude rather than non-emptiness: the reported figure must
    /// cover the slot vector the sparse id forces into existence, on top of the
    /// two payload columns, which are identical in both blocks.
    #[test]
    fn decoded_heap_bytes_charges_the_slot_vector() {
        fn block_with(ids: [u32; 2]) -> DecodedBlock {
            let mut i64_cols: ColMap<Vec<Option<i64>>> = ColMap::new();
            i64_cols.insert(ids[0], vec![Some(1i64); 4]);
            i64_cols.insert(ids[1], vec![Some(2i64); 4]);
            DecodedBlock {
                record_count: 4,
                i64_cols,
                f64_cols: ColMap::new(),
                bool_cols: ColMap::new(),
                str_cols: ColMap::new(),
                fixed_cols: ColMap::new(),
                col_lookups: Cell::new(0),
                attrs_raw_page: false,
                pages_decoded: 2,
                pages_skipped: 0,
                page_bytes_fetched: 0,
                page_bytes_decoded: 0,
            }
        }

        // Same two columns, same payloads; only the second id differs.
        let dense = block_with([0, 1]).decoded_heap_bytes();
        let sparse = block_with([0, 1000]).decoded_heap_bytes();

        // The gap the id 1000 opens. Floored below 999 slots because `Vec`
        // growth rounds the dense block's capacity up (2 slots requested, 4
        // allocated), so the exact difference is a few slots short of the id
        // gap. 900 still pins the magnitude: an implementation that charged
        // only the two columns actually present would show a difference of
        // roughly zero here, not of 900 slots.
        let slot = std::mem::size_of::<Option<Vec<Option<i64>>>>();
        let forced = 900 * slot;
        assert!(
            sparse >= dense + forced,
            "a block whose largest column id is 1000 must charge at least \
             {forced} B more than the same columns at ids 0 and 1: \
             sparse={sparse} dense={dense}"
        );
    }

    fn row(stream_ref: u32, ts: i64) -> ResolvedRow {
        ResolvedRow {
            stream_ref,
            ts_ns: ts,
            observed_ts_ns: ts + 1,
            severity_num: 9,
            severity_text: "INFO".into(),
            body: format!("body {ts}"),
            trace_id: None,
            span_id: None,
            flags: 0,
            attrs_raw: None,
            columns: Vec::new(),
            indexed_terms: Vec::new(),
            stat_winners: Vec::new(),
        }
    }

    /// Adds a dynamic attribute the way the writer does for the ordinary row
    /// that carries a name exactly once: the value goes in the column *and* is
    /// that row's winner for the name, so the value page and the stat see the
    /// same value. Tests that care about the two diverging set `stat_winners`
    /// by hand.
    fn put(r: &mut ResolvedRow, column_id: u32, v: ColumnValue) {
        r.columns.push((column_id, v.clone()));
        r.stat_winners.push((column_id, v));
    }

    #[test]
    fn roundtrip_with_mixed_presence() {
        let plans = vec![
            ColumnPlan {
                column_id: 10,
                ty: FieldType::I64,
            },
            ColumnPlan {
                column_id: 11,
                ty: FieldType::Str,
            },
        ];
        let mut rows = Vec::new();
        for i in 0..100i64 {
            let mut r = row(0, 1000 + i);
            // Column 10 present in even rows only.
            if i % 2 == 0 {
                r.columns.push((10, ColumnValue::I64(i * 3)));
            }
            // Column 11 present in first half only.
            if i < 50 {
                r.columns
                    .push((11, ColumnValue::Str(format!("s{i}").into_bytes())));
            }
            if i % 3 == 0 {
                r.trace_id = Some([i as u8; 16]);
            }
            rows.push(r);
        }
        let out = write_block(&rows, &plans, 3).expect("write");
        assert_eq!(out.record_count, 100);
        let dec = read_block(&out.v3_bytes().0, out.v3_bytes().1, &plans, 1 << 30).expect("read");
        assert_eq!(dec.record_count(), 100);

        // Fixed columns.
        let ts = dec.i64_col(COL_TS).expect("ts");
        for (i, v) in ts.iter().enumerate() {
            assert_eq!(*v, Some(1000 + i as i64));
        }
        let body = dec.str_col_fused(COL_BODY).expect("body");
        assert_eq!(body[7], Some(b"body 1007".to_vec()));

        // Dynamic presence.
        let c10 = dec.i64_col(10).expect("c10");
        for (i, v) in c10.iter().enumerate() {
            if i % 2 == 0 {
                assert_eq!(*v, Some(i as i64 * 3));
            } else {
                assert_eq!(*v, None);
            }
        }
        let c11 = dec.str_col_fused(11).expect("c11");
        assert_eq!(c11[10], Some(b"s10".to_vec()));
        assert_eq!(c11[60], None);

        // trace_id presence.
        let tr = dec.fixed_col(COL_TRACE_ID).expect("trace");
        assert_eq!(tr[0], Some(vec![0u8; 16]));
        assert_eq!(tr[1], None);
    }

    #[test]
    fn crc_mismatch_is_corrupted() {
        let rows = vec![row(0, 5), row(0, 6)];
        let out = write_block(&rows, &[], 3).expect("write");
        let mut bad = out.v3_bytes().0;
        bad[0] ^= 0xff;
        assert!(matches!(
            read_block(&bad, out.v3_bytes().1, &[], 1 << 30),
            Err(LogSegError::Corrupted(_))
        ));
    }

    #[test]
    fn stats_min_max_null_and_nan() {
        let plans = vec![
            ColumnPlan {
                column_id: 10,
                ty: FieldType::I64,
            },
            ColumnPlan {
                column_id: 11,
                ty: FieldType::F64,
            },
        ];
        let mut rows = Vec::new();
        for i in 0..10i64 {
            let mut r = row(0, i);
            if i < 6 {
                put(&mut r, 10, ColumnValue::I64(i - 2));
            }
            rows.push(r);
        }
        // f64 column: values including a NaN payload; NaN excluded from min/max.
        put(&mut rows[0], 11, ColumnValue::F64(1.5f64.to_bits()));
        put(&mut rows[1], 11, ColumnValue::F64((-3.0f64).to_bits()));
        put(
            &mut rows[2],
            11,
            ColumnValue::F64((f64::NAN.to_bits()) | 0x7),
        );
        let out = write_block(&rows, &plans, 3).expect("write");

        let s10 = out.stats.iter().find(|s| s.column_id == 10).expect("s10");
        assert_eq!(s10.min_bits, (-2i64) as u64);
        assert_eq!(s10.max_bits, 3i64 as u64);
        assert_eq!(s10.null_count, 4);
        assert!(!s10.has_nan);

        let s11 = out.stats.iter().find(|s| s.column_id == 11).expect("s11");
        assert!(s11.has_nan);
        assert_eq!(f64::from_bits(s11.min_bits), -3.0);
        assert_eq!(f64::from_bits(s11.max_bits), 1.5);
        assert_eq!(s11.null_count, 7);
    }

    /// A row whose cross-type winner for an attribute name is of another type
    /// contributes nothing but a null to that name's numeric stats, even though
    /// its losing occurrence still occupies the value page (ADR-0095 decisions
    /// 2 and 3).
    ///
    /// Rows here model a record carrying `dur` twice: once in the I64 column
    /// (id 10) and once as a Str (id 12) that wins the merge, plus the mirror
    /// case for a Bool (id 11) and an F64 (id 13). The stats must bound only
    /// the winning-type occurrences: 7 (row 1's uncontested i64), never row 0's
    /// losing 9999; `true` (row 1), never row 0's losing `false`; 2.5 (row 1),
    /// never row 0's losing -1e9.
    #[test]
    fn numstat_reflects_cross_type_winner() {
        let plans = vec![
            ColumnPlan {
                column_id: 10,
                ty: FieldType::I64,
            },
            ColumnPlan {
                column_id: 11,
                ty: FieldType::Bool,
            },
            ColumnPlan {
                column_id: 12,
                ty: FieldType::Str,
            },
            ColumnPlan {
                column_id: 13,
                ty: FieldType::F64,
            },
        ];

        // Row 0: every numeric occurrence loses to a Str occurrence of the same
        // name, so its winner maps to the Str column (12) alone.
        let mut loser = row(0, 1);
        loser.columns.push((10, ColumnValue::I64(9999)));
        loser.columns.push((11, ColumnValue::Bool(false)));
        loser
            .columns
            .push((13, ColumnValue::F64((-1e9f64).to_bits())));
        loser.columns.push((12, ColumnValue::Str(b"late".to_vec())));
        loser
            .stat_winners
            .push((12, ColumnValue::Str(b"late".to_vec())));

        // Row 1: the ordinary shape, each name carried once and winning.
        let mut winner = row(0, 2);
        put(&mut winner, 10, ColumnValue::I64(7));
        put(&mut winner, 11, ColumnValue::Bool(true));
        put(&mut winner, 13, ColumnValue::F64(2.5f64.to_bits()));

        let out = write_block(&[loser, winner], &plans, 3).expect("write");
        let stat = |cid: u32| {
            *out.stats
                .iter()
                .find(|s| s.column_id == cid)
                .unwrap_or_else(|| panic!("stat for column {cid}"))
        };

        let i64_stat = stat(10);
        assert_eq!(i64_stat.min_bits, 7i64 as u64, "losing 9999 must not widen");
        assert_eq!(i64_stat.max_bits, 7i64 as u64, "losing 9999 must not widen");
        assert_eq!(
            i64_stat.null_count, 1,
            "the cross-type loser counts as a null, like an absent attribute"
        );

        let bool_stat = stat(11);
        assert_eq!(bool_stat.min_bits, 1, "losing false must not widen");
        assert_eq!(bool_stat.max_bits, 1);
        assert_eq!(bool_stat.null_count, 1);

        let f64_stat = stat(13);
        assert_eq!(f64::from_bits(f64_stat.min_bits), 2.5);
        assert_eq!(f64::from_bits(f64_stat.max_bits), 2.5);
        assert_eq!(f64_stat.null_count, 1);

        // The losing values are still stored: the fix changes the stats, never
        // the rows. Both occurrences survive so the read side can resolve the
        // winner itself.
        let dec = read_block(&out.v3_bytes().0, out.v3_bytes().1, &plans, 1 << 30).expect("read");
        assert_eq!(dec.i64_col(10).and_then(|c| c[0]), Some(9999));
        assert_eq!(dec.bool_col(11).and_then(|c| c[0]), Some(false));
        assert_eq!(
            dec.f64_col(13).and_then(|c| c[0]).map(f64::from_bits),
            Some(-1e9)
        );
    }

    /// A planned numeric column that no row resolves still gets a stat, and
    /// that stat's `null_count` covers every row of the block. This is the
    /// case docs/log-segment-format.md's `null_count` contract turns on: a
    /// present stat is not evidence that any row resolves the column, and its
    /// bounds are the degenerate 0/0 pair.
    ///
    /// Scope: this pins the emit half, taking the plan as given. That the
    /// writer plans such a column at all, from a record-level occurrence whose
    /// merged-view winner is of another type, is decided in `writer.rs` and is
    /// not covered here.
    #[test]
    fn numstat_covers_every_row_when_none_resolves_the_column() {
        let plans = vec![
            ColumnPlan {
                column_id: 10,
                ty: FieldType::I64,
            },
            ColumnPlan {
                column_id: 12,
                ty: FieldType::Str,
            },
        ];

        // Every row carries the name as both I64 and Str, and Str wins each
        // time, so no row resolves an I64 value for a column that is planned
        // because the I64 occurrence is present.
        let rows: Vec<_> = (0..8i64)
            .map(|i| {
                let mut r = row(0, 1 + i);
                r.columns.push((10, ColumnValue::I64(9999)));
                r.columns.push((12, ColumnValue::Str(b"wins".to_vec())));
                r.stat_winners
                    .push((12, ColumnValue::Str(b"wins".to_vec())));
                r
            })
            .collect();

        let out = write_block(&rows, &plans, 3).expect("write");
        let i64_stat = *out
            .stats
            .iter()
            .find(|s| s.column_id == 10)
            .expect("a planned column keeps its stat even when nothing resolves it");

        assert_eq!(
            i64_stat.null_count, 8,
            "null_count must cover every row when no row resolves the column"
        );
        assert_eq!(i64_stat.min_bits, 0, "an all-null stat bounds nothing");
        assert_eq!(i64_stat.max_bits, 0, "an all-null stat bounds nothing");
    }

    /// A column filter decodes only the named columns' pages, leaves every
    /// other column absent, and reports how many pages it walked past. The
    /// values it does decode are identical to the all-columns decode's, so
    /// projection changes cost, never content.
    #[test]
    fn column_filter_decodes_only_the_named_columns() {
        let plans: Vec<ColumnPlan> = (10..30)
            .map(|column_id| ColumnPlan {
                column_id,
                ty: FieldType::Str,
            })
            .collect();
        let mut rows = Vec::new();
        for i in 0..64i64 {
            let mut r = row(0, 1000 + i);
            for p in &plans {
                r.columns.push((
                    p.column_id,
                    ColumnValue::Str(format!("c{}r{i}", p.column_id).into_bytes()),
                ));
            }
            rows.push(r);
        }
        let out = write_block(&rows, &plans, 3).expect("write");

        let all =
            read_block(&out.v3_bytes().0, out.v3_bytes().1, &plans, 1 << 30).expect("read all");
        assert_eq!(all.pages_skipped(), 0, "no filter skips nothing");

        let keep: ColumnIdSet = ColumnIdSet::from_iter([COL_TS, COL_STREAM_REF, 11, 17]);
        let projected = read_block_columns(
            &out.v3_bytes().0,
            out.v3_bytes().1,
            &plans,
            1 << 30,
            Some(&keep),
        )
        .expect("read");

        assert_eq!(projected.record_count(), 64);
        // Exactly the four requested columns decoded, one page each (every
        // column here is present in every row, so no presence bitmaps).
        assert_eq!(projected.pages_decoded(), 4);
        assert_eq!(
            projected.pages_decoded() + projected.pages_skipped(),
            all.pages_decoded(),
            "every page is either decoded or skipped, none invented"
        );
        assert!(
            projected.pages_skipped() >= 18,
            "the 18 unreferenced dynamic columns must be skipped, got {}",
            projected.pages_skipped()
        );

        // Kept columns decode identically to the unfiltered decode.
        assert_eq!(projected.i64_col(COL_TS), all.i64_col(COL_TS));
        assert_eq!(projected.str_col_fused(11), all.str_col_fused(11));
        assert_eq!(projected.str_col_fused(17), all.str_col_fused(17));
        // Excluded columns are absent, including fixed ones.
        assert!(projected.str_col_fused(12).is_none());
        assert!(projected.str_col_fused(COL_BODY).is_none());
        assert!(all.str_col_fused(COL_BODY).is_some());
    }

    /// `page_bytes_fetched`/`page_bytes_decoded` split each block's page bytes
    /// by the column filter (ADR-0107 decision 4). Every dynamic column here is
    /// present in every row, so each maps to exactly one page and the byte
    /// totals are the sums of those pages' stored lengths -- pinned exactly by
    /// decomposition, not by inequality: fetched is the sum over every present
    /// column, decoded is the sum over only the kept columns.
    #[test]
    fn page_byte_accounting_splits_fetched_and_decoded_by_filter() {
        let plans: Vec<ColumnPlan> = (10..15)
            .map(|column_id| ColumnPlan {
                column_id,
                ty: FieldType::Str,
            })
            .collect();
        let mut rows = Vec::new();
        for i in 0..64i64 {
            let mut r = row(0, 1000 + i);
            for p in &plans {
                r.columns.push((
                    p.column_id,
                    ColumnValue::Str(format!("c{}r{i}", p.column_id).into_bytes()),
                ));
            }
            rows.push(r);
        }
        let out = write_block(&rows, &plans, 3).expect("write");

        // Single-column decode of one raw column id: its one page's stored bytes.
        // `read_block_columns` takes raw ids and adds nothing implicit, so this
        // isolates exactly that column's page (present in every row => no
        // presence bitmap, one page per column).
        let single = |cid: u32| {
            let keep: ColumnIdSet = ColumnIdSet::from_iter([cid]);
            read_block_columns(
                &out.v3_bytes().0,
                out.v3_bytes().1,
                &plans,
                1 << 30,
                Some(&keep),
            )
            .expect("read")
            .page_bytes_decoded()
        };

        let all =
            read_block(&out.v3_bytes().0, out.v3_bytes().1, &plans, 1 << 30).expect("read all");
        let fetched = all.page_bytes_fetched();
        assert!(fetched > 0);
        assert_eq!(
            all.page_bytes_decoded(),
            fetched,
            "an all-columns decode decodes every fetched page byte"
        );

        // Fetched is the exact sum over every present column's page bytes: the
        // seven always-present fixed columns plus the five dynamic ones.
        let present: [u32; 12] = [
            COL_TS,
            COL_OBSERVED_TS,
            COL_STREAM_REF,
            COL_SEVERITY_NUM,
            COL_FLAGS,
            COL_SEVERITY_TEXT,
            COL_BODY,
            10,
            11,
            12,
            13,
            14,
        ];
        let fetched_oracle: u64 = present.iter().map(|&c| single(c)).sum();
        assert_eq!(
            fetched, fetched_oracle,
            "fetched bytes are the sum of every present column's page bytes"
        );

        // A strict projection: decoded is exactly the kept columns' page bytes,
        // fetched is unchanged, and the split is exact (decoded + skipped ==
        // fetched).
        let keep: ColumnIdSet = ColumnIdSet::from_iter([COL_TS, 11, 13]);
        let projected = read_block_columns(
            &out.v3_bytes().0,
            out.v3_bytes().1,
            &plans,
            1 << 30,
            Some(&keep),
        )
        .expect("read");
        assert_eq!(
            projected.page_bytes_fetched(),
            fetched,
            "fetched is filter-independent: every present page counts"
        );
        let kept_oracle: u64 = single(COL_TS) + single(11) + single(13);
        assert_eq!(
            projected.page_bytes_decoded(),
            kept_oracle,
            "decoded is exactly the kept columns' page bytes"
        );
        assert!(
            projected.page_bytes_decoded() < fetched,
            "a strict projection decodes strictly fewer bytes than are present: {} < {}",
            projected.page_bytes_decoded(),
            fetched
        );
        let skipped_bytes = fetched - projected.page_bytes_decoded();
        let skipped_oracle: u64 = present
            .iter()
            .filter(|c| !keep.contains(c))
            .map(|&c| single(c))
            .sum();
        assert_eq!(
            skipped_bytes, skipped_oracle,
            "skipped bytes are exactly the excluded columns' page bytes"
        );
    }

    /// [`ColumnIdSet`]'s membership test is still exact `HashSet` membership,
    /// just under a cheaper hasher (issue #843): these five shapes are the
    /// ones a hasher swap could plausibly get wrong (an empty filter, a
    /// single id, every present id, an id the schema never assigned, and no
    /// filter at all), pinned against the decoded page counts rather than
    /// just "the code ran".
    #[test]
    fn column_filter_membership_matches_expected_outcomes() {
        let plans: Vec<ColumnPlan> = (10..15)
            .map(|column_id| ColumnPlan {
                column_id,
                ty: FieldType::I64,
            })
            .collect();
        let mut rows = Vec::new();
        for i in 0..16i64 {
            let mut r = row(0, i);
            for p in &plans {
                r.columns.push((p.column_id, ColumnValue::I64(i)));
            }
            rows.push(r);
        }
        let out = write_block(&rows, &plans, 3).expect("write");
        let bytes = &out.v3_bytes().0;
        let crc = out.v3_bytes().1;

        // Every column present in this fixture: the 7 always-present fixed
        // columns (no trace/span id set) plus the 5 dynamic ones.
        let present: [u32; 12] = [
            COL_TS,
            COL_OBSERVED_TS,
            COL_STREAM_REF,
            COL_SEVERITY_NUM,
            COL_FLAGS,
            COL_SEVERITY_TEXT,
            COL_BODY,
            10,
            11,
            12,
            13,
            14,
        ];
        let decode = |filter: Option<&ColumnIdSet>| {
            read_block_columns(bytes, crc, &plans, 1 << 30, filter).expect("read")
        };

        // Case 1: empty set decodes nothing, including `ts` -- this layer
        // takes raw ids and adds nothing implicit (unlike `ColumnSelection`).
        let empty = ColumnIdSet::default();
        let got = decode(Some(&empty));
        assert_eq!(got.pages_decoded(), 0, "empty filter decodes no pages");
        assert_eq!(got.pages_skipped(), present.len());

        // Case 2: a single column decodes exactly that column.
        let one: ColumnIdSet = ColumnIdSet::from_iter([12]);
        let got = decode(Some(&one));
        assert_eq!(got.pages_decoded(), 1);
        assert_eq!(got.pages_skipped(), present.len() - 1);
        assert!(got.i64_col(12).is_some());
        assert!(got.i64_col(11).is_none());

        // Case 3: every present column, named explicitly (as opposed to
        // `None`), decodes everything and skips nothing.
        let all_named: ColumnIdSet = ColumnIdSet::from_iter(present);
        let got = decode(Some(&all_named));
        assert_eq!(got.pages_decoded(), present.len());
        assert_eq!(got.pages_skipped(), 0);

        // Case 4: an id the schema never assigned filters out everything,
        // the same as the empty set -- it does not error and it does not
        // match anything by accident.
        let unknown: ColumnIdSet = ColumnIdSet::from_iter([9_999]);
        let got = decode(Some(&unknown));
        assert_eq!(got.pages_decoded(), 0);
        assert_eq!(got.pages_skipped(), present.len());

        // Case 5: `None` is its own code path (`read_block`'s no-filter
        // shortcut), not "the set that happens to contain everything".
        let got = decode(None);
        assert_eq!(got.pages_decoded(), present.len());
        assert_eq!(got.pages_skipped(), 0);
    }

    /// A filter never weakens the integrity checks: the block crc still covers
    /// the whole block, so a corrupted byte inside a *skipped* column's page is
    /// still caught.
    #[test]
    fn column_filter_still_verifies_the_whole_block_crc() {
        let plans = vec![ColumnPlan {
            column_id: 10,
            ty: FieldType::Str,
        }];
        let mut rows = vec![row(0, 1), row(0, 2)];
        for r in &mut rows {
            r.columns.push((10, ColumnValue::Str(b"payload".to_vec())));
        }
        let out = write_block(&rows, &plans, 3).expect("write");
        let keep: ColumnIdSet = ColumnIdSet::from_iter([COL_TS, COL_STREAM_REF]);
        // Corrupt the tail, which belongs to a column the filter skips.
        let mut bad = out.v3_bytes().0;
        let last = bad.len() - 1;
        bad[last] ^= 0xff;
        assert!(matches!(
            read_block_columns(&bad, out.v3_bytes().1, &plans, 1 << 30, Some(&keep)),
            Err(LogSegError::Corrupted(_))
        ));
    }

    /// `decoded_heap_bytes` charges a dictionary-form string column its true
    /// footprint -- the distinct set once plus a narrow id per row -- not one
    /// owned `Vec<u8>` per row (ADR-0099 decision 4, deliverable 4). Pinned
    /// against a column of known distinct count so a regression to the fused
    /// figure (which would over-report by the deduplication factor) fails here.
    #[test]
    fn dict_decoded_heap_bytes_reports_dictionary_footprint() {
        const N: usize = 100;
        const DISTINCT: usize = 4;
        const LEN: usize = 5;
        let dict_vals: [&[u8]; DISTINCT] = [b"aaaaa", b"bbbbb", b"ccccc", b"ddddd"];

        let plans = vec![ColumnPlan {
            column_id: 10,
            ty: FieldType::Str,
        }];
        let mut rows = Vec::new();
        for i in 0..N {
            let mut r = row(0, i as i64);
            r.columns
                .push((10, ColumnValue::Str(dict_vals[i % DISTINCT].to_vec())));
            rows.push(r);
        }
        let out = write_block(&rows, &plans, 3).expect("write");

        // Decode only column 10 so the figure is exactly that one column's.
        let keep: ColumnIdSet = ColumnIdSet::from_iter([10]);
        let dec = read_block_columns(
            &out.v3_bytes().0,
            out.v3_bytes().1,
            &plans,
            1 << 30,
            Some(&keep),
        )
        .expect("read");

        // The column dictionary-encoded (4 distinct of 100) and is kept intact.
        let (dict, ids) = dec.str_dict(10).expect("column 10 is a dictionary page");
        assert_eq!(dict.len(), DISTINCT);
        assert_eq!(ids.len(), N);

        let opt_u32 = std::mem::size_of::<Option<u32>>();
        let vec_spine = std::mem::size_of::<Vec<u8>>();
        let opt_vec = std::mem::size_of::<Option<Vec<u8>>>();

        // New (dict) footprint: one id per row + the distinct set once.
        let dict_figure = N * opt_u32 + DISTINCT * vec_spine + DISTINCT * LEN;
        assert_eq!(
            dec.decoded_heap_bytes(),
            dict_figure,
            "decoded_heap_bytes must report the dictionary footprint"
        );

        // Old (fused) footprint the code must no longer report: one owned buffer
        // per row. On this 64-bit host dict_figure=916, fused_figure=2900.
        let fused_figure = N * opt_vec + N * LEN;
        assert!(
            dict_figure < fused_figure,
            "the dictionary form must be smaller: dict={dict_figure}, fused={fused_figure}"
        );
    }

    #[test]
    fn absent_column_occupies_no_page() {
        // Column 12 never present -> no page, decodes as absent everywhere.
        let plans = vec![ColumnPlan {
            column_id: 12,
            ty: FieldType::Bool,
        }];
        let rows = vec![row(0, 1), row(0, 2)];
        let out = write_block(&rows, &plans, 3).expect("write");
        let dec = read_block(&out.v3_bytes().0, out.v3_bytes().1, &plans, 1 << 30).expect("read");
        assert!(dec.bool_col(12).is_none());
    }

    mod column_id_set_proptest {
        use super::*;
        use proptest::prelude::*;

        proptest! {
            #![proptest_config(ProptestConfig::with_cases(1000))]

            // `ColumnIdSet` disagrees with `HashSet`'s default hasher on
            // bucket layout, never on membership: for any set of ids and any
            // probed id, `contains` must agree with the plain
            // `std::HashSet<u32>` reference oracle (issue #843).
            #[test]
            fn contains_matches_std_hashset_oracle(
                ids in proptest::collection::vec(0u32..2000, 0..200),
                probes in proptest::collection::vec(0u32..2000, 1..50),
            ) {
                let oracle: std::collections::HashSet<u32> = ids.iter().copied().collect();
                let fast: ColumnIdSet = ids.iter().copied().collect();
                for p in &probes {
                    prop_assert_eq!(oracle.contains(p), fast.contains(p));
                }
                prop_assert_eq!(oracle.len(), fast.len());
            }
        }
    }
}
