//! Fixture-corpus detection gate (ADR-0028 decision 6): every committed
//! synthetic series with known ground truth must be classified with the
//! correct kind, and (when it has a change) located within the tolerance
//! window recorded in the fixture header. The corpus is generated by
//! `examples/gen_fixtures.rs`; regenerate it with
//! `cargo run -p ravel-analytics --example gen_fixtures`.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::path::PathBuf;

use ravel_analytics::{ChangeKind, ChangePointParams, change_point};

const STEP_NS: i64 = 60_000_000_000;

struct Fixture {
    kind: String,
    change_index: i64,
    tolerance: usize,
    series: Vec<(i64, f64)>,
}

fn parse(name: &str) -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(format!("{name}.csv"));
    let text = std::fs::read_to_string(&path).expect("fixture file exists; run the generator");

    let mut kind = String::new();
    let mut change_index = -1i64;
    let mut tolerance = 0usize;
    let mut series = Vec::new();
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("# kind=") {
            kind = rest.to_string();
        } else if let Some(rest) = line.strip_prefix("# change_index=") {
            change_index = rest.parse().expect("change_index is an integer");
        } else if let Some(rest) = line.strip_prefix("# tolerance=") {
            tolerance = rest.parse().expect("tolerance is an integer");
        } else if line == "ts_ns,value" || line.is_empty() {
            continue;
        } else {
            let (ts, value) = line.split_once(',').expect("row is ts,value");
            series.push((
                ts.parse().expect("ts is an integer"),
                value.parse().expect("value is a float"),
            ));
        }
    }
    Fixture {
        kind,
        change_index,
        tolerance,
        series,
    }
}

fn kind_name(kind: ChangeKind) -> &'static str {
    match kind {
        ChangeKind::Spike => "Spike",
        ChangeKind::Dip => "Dip",
        ChangeKind::StepChange => "StepChange",
        ChangeKind::TrendChange => "TrendChange",
        ChangeKind::DistributionChange => "DistributionChange",
        ChangeKind::Stationary => "Stationary",
        ChangeKind::Indeterminable => "Indeterminable",
    }
}

fn check(name: &str) {
    let f = parse(name);
    let result = change_point(&f.series, &ChangePointParams { downsample: false })
        .expect("fixtures are within budget");

    assert_eq!(
        kind_name(result.kind),
        f.kind,
        "fixture {name}: expected kind {}, got {:?} (score {})",
        f.kind,
        result.kind,
        result.score
    );

    if f.change_index < 0 {
        assert_eq!(result.ts_ns, None, "fixture {name}: expected no location");
    } else {
        let expected_ts = f.change_index * STEP_NS;
        let got = result.ts_ns.expect("a located change");
        let tol_ns = f.tolerance as i64 * STEP_NS;
        assert!(
            (got - expected_ts).abs() <= tol_ns,
            "fixture {name}: located at index {}, expected {} +/- {}",
            got / STEP_NS,
            f.change_index,
            f.tolerance
        );
    }
}

#[test]
fn step_fixture() {
    check("step");
}

#[test]
fn spike_fixture() {
    check("spike");
}

#[test]
fn dip_fixture() {
    check("dip");
}

#[test]
fn trend_break_fixture() {
    check("trend_break");
}

#[test]
fn variance_shift_fixture() {
    check("variance_shift");
}

#[test]
fn stationary_fixture() {
    check("stationary");
}

#[test]
fn constant_fixture() {
    check("constant");
}
